//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AventasApi.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class AtributosxColeccion
    {
        public int IdAtributoxColeccion { get; set; }
        public Nullable<int> IdColeccion { get; set; }
        public string Descripcion1 { get; set; }
        public string Descripcion2 { get; set; }
        public string IdLinea { get; set; }
        public Nullable<int> CodigoAtributo { get; set; }
    
        public virtual Colecciones Colecciones { get; set; }
        public virtual MaestroLinea MaestroLinea { get; set; }
    }
}
