//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AventasApi.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class DistribucionxTalla
    {
        public int IdDistribucion { get; set; }
        public Nullable<int> IdTallaxGrupo { get; set; }
        public string NombreDistribucion { get; set; }
        public string NombreTalla { get; set; }
        public string Cantidad { get; set; }
    
        public virtual TallasXGrupo TallasXGrupo { get; set; }
    }
}
