//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AventasApi.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class FotografiasXProducto
    {
        public int IdFotografia { get; set; }
        public string Codigo { get; set; }
        public string Descripcion { get; set; }
        public string FotografiaProducto { get; set; }
        public Nullable<int> IdProducto { get; set; }
        public string CodigoColor { get; set; }
        public Nullable<bool> Principal { get; set; }
    
        public virtual Colores Colores { get; set; }
        public virtual ProductosxColeccion ProductosxColeccion { get; set; }
    }
}
