//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AventasApi.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class GrupoTalla
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GrupoTalla()
        {
            this.ProductosxColeccion = new HashSet<ProductosxColeccion>();
            this.TallasXGrupo = new HashSet<TallasXGrupo>();
        }
    
        public string CodigoGrupoTalla { get; set; }
        public string Descripcion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductosxColeccion> ProductosxColeccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TallasXGrupo> TallasXGrupo { get; set; }
    }
}
