//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AventasApi.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class LimiteCreditoxCliente
    {
        public int IdLimiteCreditoxCliente { get; set; }
        public string Descripcion { get; set; }
        public Nullable<decimal> Valor { get; set; }
        public string CodigoCliente { get; set; }
    
        public virtual Clientes Clientes { get; set; }
    }
}
