//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AventasApi.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class PedidosxCliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PedidosxCliente()
        {
            this.FirmasxPedido = new HashSet<FirmasxPedido>();
            this.PedidosDetalle = new HashSet<PedidosDetalle>();
        }
    
        public string PedidoId { get; set; }
        public Nullable<int> IdTipoPedido { get; set; }
        public Nullable<int> IdColeccion { get; set; }
        public string CodigoCliente { get; set; }
        public string AcuerdoVenta { get; set; }
        public string EmpresaId { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<System.DateTime> FechaEntrega { get; set; }
        public string CodigoAsesor { get; set; }
        public string Observacion { get; set; }
        public Nullable<decimal> TotalUnidades { get; set; }
        public Nullable<decimal> Subtotal { get; set; }
        public Nullable<decimal> TotalImpuesto { get; set; }
        public Nullable<decimal> TotalDescuento { get; set; }
        public Nullable<decimal> TotalPedido { get; set; }
        public Nullable<bool> Mocked { get; set; }
        public Nullable<decimal> Accuracy { get; set; }
        public Nullable<decimal> Altitude { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public string Error { get; set; }
        public string IdLinea { get; set; }
        public string idMoneda { get; set; }
        public Nullable<int> IdEstado { get; set; }
    
        public virtual Asesores Asesores { get; set; }
        public virtual Clientes Clientes { get; set; }
        public virtual Colecciones Colecciones { get; set; }
        public virtual Empresa Empresa { get; set; }
        public virtual EstadosPedido EstadosPedido { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FirmasxPedido> FirmasxPedido { get; set; }
        public virtual MaestroLinea MaestroLinea { get; set; }
        public virtual MaestroMoneda MaestroMoneda { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PedidosDetalle> PedidosDetalle { get; set; }
        public virtual TiposdePedido TiposdePedido { get; set; }
    }
}
