//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AventasApi.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrioridadAsignacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PrioridadAsignacion()
        {
            this.AsignacionxAsesor = new HashSet<AsignacionxAsesor>();
        }
    
        public int idPrioridad { get; set; }
        public string NombrePrioridad { get; set; }
        public Nullable<bool> Estatus { get; set; }
        public string ColorBorde { get; set; }
        public string ColorRelleno { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AsignacionxAsesor> AsignacionxAsesor { get; set; }
    }
}
