//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AventasApi.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class RutasxAsesor
    {
        public int IdRutasxAsesor { get; set; }
        public string CodigoRuta { get; set; }
        public string CodigoAsesor { get; set; }
    
        public virtual Asesores Asesores { get; set; }
        public virtual Rutas Rutas { get; set; }
    }
}
