//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AventasApi.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rutas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rutas()
        {
            this.ClientesxRuta = new HashSet<ClientesxRuta>();
            this.RutasxAsesor = new HashSet<RutasxAsesor>();
        }
    
        public string CodigoRuta { get; set; }
        public string EmpresaId { get; set; }
        public string Nombre { get; set; }
        public Nullable<bool> Revision { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientesxRuta> ClientesxRuta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RutasxAsesor> RutasxAsesor { get; set; }
    }
}
