//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AventasApi.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class TiposdePagoDetalle
    {
        public int IdTipoPagoDetalle { get; set; }
        public string Codigo { get; set; }
        public string CodigoDetalle { get; set; }
        public string Descripcion { get; set; }
        public string EmpresaId { get; set; }
        public Nullable<int> IdTipoPago { get; set; }
    
        public virtual Empresa Empresa { get; set; }
        public virtual TiposdePago TiposdePago { get; set; }
    }
}
