//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcuerdosxCliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AcuerdosxCliente()
        {
            this.AcuerdosxClienteDetalle = new HashSet<AcuerdosxClienteDetalle>();
            this.SubFacturasxCliente = new HashSet<SubFacturasxCliente>();
            this.FacturasxCliente = new HashSet<FacturasxCliente>();
        }
    
        public string IdAcuerdoxCliente { get; set; }
        public string CodigoCliente { get; set; }
        public Nullable<int> IdTipoPedido { get; set; }
        public string IdMoneda { get; set; }
        public string EmpresaId { get; set; }
        public string Tipo { get; set; }
        public string TipoPago { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<decimal> Saldo { get; set; }
        public Nullable<decimal> Liberado { get; set; }
        public Nullable<decimal> Facturado { get; set; }
        public Nullable<decimal> Entregado { get; set; }
        public string IdLinea { get; set; }
        public Nullable<System.DateTime> Desde { get; set; }
        public Nullable<System.DateTime> Hasta { get; set; }
    
        public virtual Empresa Empresa { get; set; }
        public virtual MaestroLinea MaestroLinea { get; set; }
        public virtual MaestroMoneda MaestroMoneda { get; set; }
        public virtual TiposdePedido TiposdePedido { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AcuerdosxClienteDetalle> AcuerdosxClienteDetalle { get; set; }
        public virtual Clientes Clientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubFacturasxCliente> SubFacturasxCliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FacturasxCliente> FacturasxCliente { get; set; }
    }
}
