//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asesores
    {
        public string CodigoAsesor { get; set; }
        public string Nombre { get; set; }
        public string EmpresaId { get; set; }
        public string Usuario { get; set; }
        public Nullable<bool> Revision { get; set; }
        public Nullable<int> CorrelativoPedidos { get; set; }
        public Nullable<int> CorrelativoRecibos { get; set; }
        public string InicialesNombre { get; set; }
        public string Diario { get; set; }
        public Nullable<bool> Activo { get; set; }
        public int AsesorId { get; set; }
        public Nullable<int> CorrelativoDevolucion { get; set; }
    }
}
