//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asesores
    {
        public string CodigoAsesor { get; set; }
        public string Nombre { get; set; }
        public string EmpresaId { get; set; }
        public string Usuario { get; set; }
        public Nullable<bool> Revision { get; set; }
        public Nullable<int> CorrelativoPedidos { get; set; }
        public Nullable<int> CorrelativoRecibos { get; set; }
        public string InicialesNombre { get; set; }
        public string Diario { get; set; }
        public Nullable<bool> Activo { get; set; }
        public int AsesorId { get; set; }
        public Nullable<int> CorrelativoDevolucion { get; set; }
        public string ConstanteGira { get; set; }
        public int CorrelativoGira { get; set; }
        public byte[] firma { get; set; }
        public Nullable<int> CorrelativoInventario { get; set; }
    }
}
