//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asesores
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Asesores()
        {
            this.AsignacionxAsesor = new HashSet<AsignacionxAsesor>();
            this.BitacoraGeoposicion = new HashSet<BitacoraGeoposicion>();
            this.BitacoraVisitasCliente = new HashSet<BitacoraVisitasCliente>();
            this.RutasxAsesor = new HashSet<RutasxAsesor>();
            this.PedidosxCliente = new HashSet<PedidosxCliente>();
        }
    
        public string CodigoAsesor { get; set; }
        public string Nombre { get; set; }
        public string EmpresaId { get; set; }
        public string Usuario { get; set; }
        public Nullable<bool> Revision { get; set; }
        public Nullable<int> CorrelativoPedidos { get; set; }
        public Nullable<int> CorrelativoRecibos { get; set; }
        public string InicialesNombre { get; set; }
        public string Diario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AsignacionxAsesor> AsignacionxAsesor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BitacoraGeoposicion> BitacoraGeoposicion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BitacoraVisitasCliente> BitacoraVisitasCliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RutasxAsesor> RutasxAsesor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PedidosxCliente> PedidosxCliente { get; set; }
    }
}
