//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class AsignacionxAsesor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AsignacionxAsesor()
        {
            this.AsignacionxAsesorDetalle = new HashSet<AsignacionxAsesorDetalle>();
            this.BitacoraGeoposicion = new HashSet<BitacoraGeoposicion>();
        }
    
        public int IdAsignacionxAsesor { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string CodigoCliente { get; set; }
        public string CodigoAsesor { get; set; }
        public string Usuario { get; set; }
        public Nullable<System.DateTime> FechaAsignacion { get; set; }
        public Nullable<int> Orden { get; set; }
        public Nullable<System.DateTime> HoraInicio { get; set; }
        public Nullable<System.DateTime> HoraFinal { get; set; }
        public Nullable<int> idPrioridad { get; set; }
        public Nullable<int> idTipoVisita { get; set; }
        public string Observacion { get; set; }
        public Nullable<decimal> latitudeCheckIn { get; set; }
        public Nullable<decimal> longitudeCheckIn { get; set; }
        public Nullable<System.DateTime> fechaCheckIn { get; set; }
        public Nullable<decimal> latitudeCheckOut { get; set; }
        public Nullable<decimal> longitudeCheckOut { get; set; }
        public Nullable<System.DateTime> fechaCheckOut { get; set; }
        public bool BloqueoCheckin { get; set; }
        public bool BloqueoCheckout { get; set; }
        public bool Cancelada { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AsignacionxAsesorDetalle> AsignacionxAsesorDetalle { get; set; }
        public virtual PrioridadAsignacion PrioridadAsignacion { get; set; }
        public virtual TipoVisitaCliente TipoVisitaCliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BitacoraGeoposicion> BitacoraGeoposicion { get; set; }
    }
}
