//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class AsignacionxAsesorDetalle
    {
        public int idAsignacionDetalle { get; set; }
        public Nullable<int> idAsignacionxAsesor { get; set; }
        public Nullable<System.DateTime> FechaAsignacion { get; set; }
        public Nullable<System.DateTime> HoraInicio { get; set; }
        public Nullable<System.DateTime> HoraFin { get; set; }
        public Nullable<int> idTipoVisita { get; set; }
    
        public virtual AsignacionxAsesor AsignacionxAsesor { get; set; }
        public virtual TipoVisitaCliente TipoVisitaCliente { get; set; }
    }
}
