//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class AsignacionxAsesorDetalle
    {
        public int idAsignacionDetalle { get; set; }
        public Nullable<int> idAsignacionxAsesor { get; set; }
        public Nullable<System.DateTime> FechaAsignacion { get; set; }
        public Nullable<System.DateTime> HoraInicio { get; set; }
        public Nullable<System.DateTime> HoraFin { get; set; }
        public Nullable<int> idTipoVisita { get; set; }
    
        public virtual TipoVisitaCliente TipoVisitaCliente { get; set; }
        public virtual AsignacionxAsesor AsignacionxAsesor { get; set; }
    }
}
