//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class AVentasEntities : DbContext
    {
        public AVentasEntities()
            : base("name=AVentasEntities")
        {
            var objectContext = (this as IObjectContextAdapter).ObjectContext; objectContext.CommandTimeout = 1440;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AcuerdosxCliente> AcuerdosxCliente { get; set; }
        public virtual DbSet<AcuerdosxClienteDetalle> AcuerdosxClienteDetalle { get; set; }
        public virtual DbSet<AsignacionxAsesorDetalle> AsignacionxAsesorDetalle { get; set; }
        public virtual DbSet<AtributosxColeccion> AtributosxColeccion { get; set; }
        public virtual DbSet<AtributosxProducto> AtributosxProducto { get; set; }
        public virtual DbSet<Bancos> Bancos { get; set; }
        public virtual DbSet<Clientes> Clientes { get; set; }
        public virtual DbSet<ClientesxRuta> ClientesxRuta { get; set; }
        public virtual DbSet<Colores> Colores { get; set; }
        public virtual DbSet<ColoresxProducto> ColoresxProducto { get; set; }
        public virtual DbSet<Configuraciones> Configuraciones { get; set; }
        public virtual DbSet<CuentasBancarias> CuentasBancarias { get; set; }
        public virtual DbSet<DistribucionxTalla> DistribucionxTalla { get; set; }
        public virtual DbSet<EdadesxColeccion> EdadesxColeccion { get; set; }
        public virtual DbSet<Empresa> Empresa { get; set; }
        public virtual DbSet<Errores> Errores { get; set; }
        public virtual DbSet<EstadosPedido> EstadosPedido { get; set; }
        public virtual DbSet<FacturasxCliente> FacturasxCliente { get; set; }
        public virtual DbSet<FirmasxPedido> FirmasxPedido { get; set; }
        public virtual DbSet<FormularioIntroDetalle> FormularioIntroDetalle { get; set; }
        public virtual DbSet<FormularioIntroDetallexRoles> FormularioIntroDetallexRoles { get; set; }
        public virtual DbSet<FormularioIntroEncabezado> FormularioIntroEncabezado { get; set; }
        public virtual DbSet<GrupoTalla> GrupoTalla { get; set; }
        public virtual DbSet<LimiteCreditoxCliente> LimiteCreditoxCliente { get; set; }
        public virtual DbSet<LineasxColeccion> LineasxColeccion { get; set; }
        public virtual DbSet<MaestroEdad> MaestroEdad { get; set; }
        public virtual DbSet<MaestroGrupoPrecio> MaestroGrupoPrecio { get; set; }
        public virtual DbSet<MaestroLinea> MaestroLinea { get; set; }
        public virtual DbSet<MaestroMoneda> MaestroMoneda { get; set; }
        public virtual DbSet<MonedasxEmpresa> MonedasxEmpresa { get; set; }
        public virtual DbSet<PrioridadAsignacion> PrioridadAsignacion { get; set; }
        public virtual DbSet<ProductosxColeccion> ProductosxColeccion { get; set; }
        public virtual DbSet<RazonNoVentaCausa> RazonNoVentaCausa { get; set; }
        public virtual DbSet<RazonNoVentaTipo> RazonNoVentaTipo { get; set; }
        public virtual DbSet<RecibosDetalle> RecibosDetalle { get; set; }
        public virtual DbSet<Rutas> Rutas { get; set; }
        public virtual DbSet<SubFacturasxCliente> SubFacturasxCliente { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TallasXGrupo> TallasXGrupo { get; set; }
        public virtual DbSet<TallasxProducto> TallasxProducto { get; set; }
        public virtual DbSet<TiposdeColeccion> TiposdeColeccion { get; set; }
        public virtual DbSet<TiposdePago> TiposdePago { get; set; }
        public virtual DbSet<TiposdePagoDetalle> TiposdePagoDetalle { get; set; }
        public virtual DbSet<TiposdePedido> TiposdePedido { get; set; }
        public virtual DbSet<TipoVisitaCliente> TipoVisitaCliente { get; set; }
        public virtual DbSet<Acciones> Acciones { get; set; }
        public virtual DbSet<vw_AtributosxColeccion> vw_AtributosxColeccion { get; set; }
        public virtual DbSet<vw_ClientesxRuta> vw_ClientesxRuta { get; set; }
        public virtual DbSet<vw_ColoresxProducto> vw_ColoresxProducto { get; set; }
        public virtual DbSet<vw_FisicoDisponible> vw_FisicoDisponible { get; set; }
        public virtual DbSet<vw_TallasxProducto> vw_TallasxProducto { get; set; }
        public virtual DbSet<RecibosxCliente> RecibosxCliente { get; set; }
        public virtual DbSet<GrupoImpuestoArticulo> GrupoImpuestoArticulo { get; set; }
        public virtual DbSet<GrupoImpuestoCliente> GrupoImpuestoCliente { get; set; }
        public virtual DbSet<ComunidadAutonoma> ComunidadAutonoma { get; set; }
        public virtual DbSet<EmpresaTransporte> EmpresaTransporte { get; set; }
        public virtual DbSet<TransportePrecioCaja> TransportePrecioCaja { get; set; }
        public virtual DbSet<PreciosxProducto> PreciosxProducto { get; set; }
        public virtual DbSet<FisicoDisponible> FisicoDisponible { get; set; }
        public virtual DbSet<PrecioEspecifico> PrecioEspecifico { get; set; }
        public virtual DbSet<ClienteContado> ClienteContado { get; set; }
        public virtual DbSet<PedidosDetalle> PedidosDetalle { get; set; }
        public virtual DbSet<Funciones> Funciones { get; set; }
        public virtual DbSet<Funciones_Roles> Funciones_Roles { get; set; }
        public virtual DbSet<Pantallas> Pantallas { get; set; }
        public virtual DbSet<Pantallas_Funciones> Pantallas_Funciones { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<PantallasxUsuario> PantallasxUsuario { get; set; }
        public virtual DbSet<Usuario_Rol> Usuario_Rol { get; set; }
        public virtual DbSet<Usuarios_Empresas> Usuarios_Empresas { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
        public virtual DbSet<TiposIngreso> TiposIngreso { get; set; }
        public virtual DbSet<GrupoOpcionesDetalle> GrupoOpcionesDetalle { get; set; }
        public virtual DbSet<GrupoOpciones> GrupoOpciones { get; set; }
        public virtual DbSet<Encuesta> Encuesta { get; set; }
        public virtual DbSet<PreguntasOpciones> PreguntasOpciones { get; set; }
        public virtual DbSet<Preguntas> Preguntas { get; set; }
        public virtual DbSet<Empresa_Encuesta> Empresa_Encuesta { get; set; }
        public virtual DbSet<Secciones_Usuarios> Secciones_Usuarios { get; set; }
        public virtual DbSet<RespuestaDetalle> RespuestaDetalle { get; set; }
        public virtual DbSet<Respuestas> Respuestas { get; set; }
        public virtual DbSet<LogSesion> LogSesion { get; set; }
        public virtual DbSet<FotografiasXProducto> FotografiasXProducto { get; set; }
        public virtual DbSet<Colecciones> Colecciones { get; set; }
        public virtual DbSet<PedidosDetalleFlotante> PedidosDetalleFlotante { get; set; }
        public virtual DbSet<RecibosDetalleFlotante> RecibosDetalleFlotante { get; set; }
        public virtual DbSet<Secciones> Secciones { get; set; }
        public virtual DbSet<Secciones_Encuesta> Secciones_Encuesta { get; set; }
        public virtual DbSet<RecibosxClienteFlotante> RecibosxClienteFlotante { get; set; }
        public virtual DbSet<DocumentosTransitoxFactura> DocumentosTransitoxFactura { get; set; }
        public virtual DbSet<PreguntasAnidadas> PreguntasAnidadas { get; set; }
        public virtual DbSet<PreguntasOpcionesAnidadas> PreguntasOpcionesAnidadas { get; set; }
        public virtual DbSet<RespuestaAnidadaDetalle> RespuestaAnidadaDetalle { get; set; }
        public virtual DbSet<ListasPreciosPaquetes> ListasPreciosPaquetes { get; set; }
        public virtual DbSet<MaestroBodegaAlmacenes> MaestroBodegaAlmacenes { get; set; }
        public virtual DbSet<MaestroBodegaSitios> MaestroBodegaSitios { get; set; }
        public virtual DbSet<PaqueteBodegaEspecifico> PaqueteBodegaEspecifico { get; set; }
        public virtual DbSet<RecibosProforma> RecibosProforma { get; set; }
        public virtual DbSet<RecibosProformaDetalle> RecibosProformaDetalle { get; set; }
        public virtual DbSet<LogProforma> LogProforma { get; set; }
        public virtual DbSet<LogRecibo> LogRecibo { get; set; }
        public virtual DbSet<AsignacionxAsesor> AsignacionxAsesor { get; set; }
        public virtual DbSet<BitacoraGeoposicion> BitacoraGeoposicion { get; set; }
        public virtual DbSet<BitacoraVisitasCliente> BitacoraVisitasCliente { get; set; }
        public virtual DbSet<PedidosxCliente> PedidosxCliente { get; set; }
        public virtual DbSet<PedidosxClienteFlotante> PedidosxClienteFlotante { get; set; }
        public virtual DbSet<RutasxAsesor> RutasxAsesor { get; set; }
        public virtual DbSet<Usuarios_Asesores> Usuarios_Asesores { get; set; }
        public virtual DbSet<Asesores> Asesores { get; set; }
        public virtual DbSet<UbicacionesXAlmacen> UbicacionesXAlmacen { get; set; }
        public virtual DbSet<Descuento> Descuento { get; set; }
        public virtual DbSet<DescuentoDetalle> DescuentoDetalle { get; set; }
        public virtual DbSet<MotivosDevolucion> MotivosDevolucion { get; set; }
        public virtual DbSet<MotivosDevolucionDetalle> MotivosDevolucionDetalle { get; set; }
        public virtual DbSet<MotivosDevConAprobacion> MotivosDevConAprobacion { get; set; }
        public virtual DbSet<Devolucion> Devolucion { get; set; }
        public virtual DbSet<AprobacionDevoluciones> AprobacionDevoluciones { get; set; }
        public virtual DbSet<vw_ColeccionesBodegaEspecifico> vw_ColeccionesBodegaEspecifico { get; set; }
        public virtual DbSet<CuotasXAcuerdo> CuotasXAcuerdo { get; set; }
        public virtual DbSet<FacturasEnCuotasAcuerdos> FacturasEnCuotasAcuerdos { get; set; }
        public virtual DbSet<PagosAFacturasDeCuotas> PagosAFacturasDeCuotas { get; set; }
        public virtual DbSet<PromesaPago> PromesaPago { get; set; }
        public virtual DbSet<BitacoraNoVentaEnVisitas> BitacoraNoVentaEnVisitas { get; set; }
        public virtual DbSet<RazonesNoVenta> RazonesNoVenta { get; set; }
        public virtual DbSet<Estado> Estado { get; set; }
        public virtual DbSet<GastosViajeDetalle> GastosViajeDetalle { get; set; }
        public virtual DbSet<TipoGastoViaje> TipoGastoViaje { get; set; }
        public virtual DbSet<GastoViajeGrupoImpuesto> GastoViajeGrupoImpuesto { get; set; }
        public virtual DbSet<CategoriaTipoGastoViaje> CategoriaTipoGastoViaje { get; set; }
        public virtual DbSet<SaleStatus> SaleStatus { get; set; }
        public virtual DbSet<AnticiposxCliente> AnticiposxCliente { get; set; }
        public virtual DbSet<Combustibles> Combustibles { get; set; }
        public virtual DbSet<DescuentoEnAcuerdo> DescuentoEnAcuerdo { get; set; }
        public virtual DbSet<DocumentosAplicadosAFacturas> DocumentosAplicadosAFacturas { get; set; }
        public virtual DbSet<UsuarioLinea> UsuarioLinea { get; set; }
        public virtual DbSet<ChequesContabilizados> ChequesContabilizados { get; set; }
        public virtual DbSet<MotivoTiempoFuera> MotivoTiempoFuera { get; set; }
        public virtual DbSet<TiempoFueraAgenda> TiempoFueraAgenda { get; set; }
        public virtual DbSet<DepositoRecibo> DepositoRecibo { get; set; }
        public virtual DbSet<DefectoDevolucion> DefectoDevolucion { get; set; }
        public virtual DbSet<OperacionDevolucion> OperacionDevolucion { get; set; }
        public virtual DbSet<ClasificacionDevolucion> ClasificacionDevolucion { get; set; }
        public virtual DbSet<DevolucionDetalle> DevolucionDetalle { get; set; }
        public virtual DbSet<BaseColorImpuesto> BaseColorImpuesto { get; set; }
        public virtual DbSet<DireccionesCliente> DireccionesCliente { get; set; }
        public virtual DbSet<DetalleFacturado> DetalleFacturado { get; set; }
        public virtual DbSet<InventarioDetalle> InventarioDetalle { get; set; }
        public virtual DbSet<InventariosCliente> InventariosCliente { get; set; }
    
        public virtual ObjectResult<CuentaCorriente_Result> CuentaCorriente(string codigoCliente)
        {
            var codigoClienteParameter = codigoCliente != null ?
                new ObjectParameter("CodigoCliente", codigoCliente) :
                new ObjectParameter("CodigoCliente", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CuentaCorriente_Result>("CuentaCorriente", codigoClienteParameter);
        }
    
        public virtual ObjectResult<CuentaCorriente2_Result> CuentaCorriente2(string codigoCliente)
        {
            var codigoClienteParameter = codigoCliente != null ?
                new ObjectParameter("CodigoCliente", codigoCliente) :
                new ObjectParameter("CodigoCliente", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CuentaCorriente2_Result>("CuentaCorriente2", codigoClienteParameter);
        }
    
        public virtual ObjectResult<EstadisticaVisita_Result> EstadisticaVisita(Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFin, string user)
        {
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("FechaInicio", fechaInicio) :
                new ObjectParameter("FechaInicio", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("FechaFin", fechaFin) :
                new ObjectParameter("FechaFin", typeof(System.DateTime));
    
            var userParameter = user != null ?
                new ObjectParameter("User", user) :
                new ObjectParameter("User", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EstadisticaVisita_Result>("EstadisticaVisita", fechaInicioParameter, fechaFinParameter, userParameter);
        }
    
        public virtual ObjectResult<PResumenCredito_Result> PResumenCredito()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PResumenCredito_Result>("PResumenCredito");
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual ObjectResult<SP_VISITASPORMES_Result1> SP_VISITASPORMES(string user)
        {
            var userParameter = user != null ?
                new ObjectParameter("User", user) :
                new ObjectParameter("User", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_VISITASPORMES_Result1>("SP_VISITASPORMES", userParameter);
        }
    
        public virtual ObjectResult<PRODUCTOSDEFACTURA_Result> PRODUCTOSDEFACTURA(string numFactura)
        {
            var numFacturaParameter = numFactura != null ?
                new ObjectParameter("numFactura", numFactura) :
                new ObjectParameter("numFactura", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PRODUCTOSDEFACTURA_Result>("PRODUCTOSDEFACTURA", numFacturaParameter);
        }
    
        public virtual ObjectResult<VisitasCliente_Result> VisitasCliente(string codigoCliente)
        {
            var codigoClienteParameter = codigoCliente != null ?
                new ObjectParameter("CodigoCliente", codigoCliente) :
                new ObjectParameter("CodigoCliente", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VisitasCliente_Result>("VisitasCliente", codigoClienteParameter);
        }
    
        public virtual ObjectResult<VisitasClienteGlobal_Result> VisitasClienteGlobal(Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFinal)
        {
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("FechaInicio", fechaInicio) :
                new ObjectParameter("FechaInicio", typeof(System.DateTime));
    
            var fechaFinalParameter = fechaFinal.HasValue ?
                new ObjectParameter("FechaFinal", fechaFinal) :
                new ObjectParameter("FechaFinal", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VisitasClienteGlobal_Result>("VisitasClienteGlobal", fechaInicioParameter, fechaFinalParameter);
        }
    
        public virtual ObjectResult<VisitasClientePorAsesor_Result> VisitasClientePorAsesor(string codigoAsesor, Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFinal)
        {
            var codigoAsesorParameter = codigoAsesor != null ?
                new ObjectParameter("CodigoAsesor", codigoAsesor) :
                new ObjectParameter("CodigoAsesor", typeof(string));
    
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("FechaInicio", fechaInicio) :
                new ObjectParameter("FechaInicio", typeof(System.DateTime));
    
            var fechaFinalParameter = fechaFinal.HasValue ?
                new ObjectParameter("FechaFinal", fechaFinal) :
                new ObjectParameter("FechaFinal", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VisitasClientePorAsesor_Result>("VisitasClientePorAsesor", codigoAsesorParameter, fechaInicioParameter, fechaFinalParameter);
        }
    
        public virtual ObjectResult<SP_ObtencionFacturas_Result> SP_ObtencionFacturas(string codigoProducto, string color, string cliente)
        {
            var codigoProductoParameter = codigoProducto != null ?
                new ObjectParameter("codigoProducto", codigoProducto) :
                new ObjectParameter("codigoProducto", typeof(string));
    
            var colorParameter = color != null ?
                new ObjectParameter("color", color) :
                new ObjectParameter("color", typeof(string));
    
            var clienteParameter = cliente != null ?
                new ObjectParameter("cliente", cliente) :
                new ObjectParameter("cliente", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ObtencionFacturas_Result>("SP_ObtencionFacturas", codigoProductoParameter, colorParameter, clienteParameter);
        }
    
        public virtual int SP_FacturasxCliente_UpdateSaldoXCliente(string cLIENTE, string eMPRESA)
        {
            var cLIENTEParameter = cLIENTE != null ?
                new ObjectParameter("CLIENTE", cLIENTE) :
                new ObjectParameter("CLIENTE", typeof(string));
    
            var eMPRESAParameter = eMPRESA != null ?
                new ObjectParameter("EMPRESA", eMPRESA) :
                new ObjectParameter("EMPRESA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_FacturasxCliente_UpdateSaldoXCliente", cLIENTEParameter, eMPRESAParameter);
        }
    
        public virtual int SP_SubFacturasxCliente_UpdateSaldoXCliente(string cLIENTE, string eMPRESA)
        {
            var cLIENTEParameter = cLIENTE != null ?
                new ObjectParameter("CLIENTE", cLIENTE) :
                new ObjectParameter("CLIENTE", typeof(string));
    
            var eMPRESAParameter = eMPRESA != null ?
                new ObjectParameter("EMPRESA", eMPRESA) :
                new ObjectParameter("EMPRESA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_SubFacturasxCliente_UpdateSaldoXCliente", cLIENTEParameter, eMPRESAParameter);
        }
    
        public virtual ObjectResult<SP_ObtenerProductosRMA_Result> SP_ObtenerProductosRMA(string rma, string pais)
        {
            var rmaParameter = rma != null ?
                new ObjectParameter("rma", rma) :
                new ObjectParameter("rma", typeof(string));
    
            var paisParameter = pais != null ?
                new ObjectParameter("pais", pais) :
                new ObjectParameter("pais", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ObtenerProductosRMA_Result>("SP_ObtenerProductosRMA", rmaParameter, paisParameter);
        }
    
        public virtual int SP_Clientes_UpdateHabilitado(string codigoAsesor, string empresa)
        {
            var codigoAsesorParameter = codigoAsesor != null ?
                new ObjectParameter("CodigoAsesor", codigoAsesor) :
                new ObjectParameter("CodigoAsesor", typeof(string));
    
            var empresaParameter = empresa != null ?
                new ObjectParameter("Empresa", empresa) :
                new ObjectParameter("Empresa", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Clientes_UpdateHabilitado", codigoAsesorParameter, empresaParameter);
        }
    
        public virtual int SP_TrasladoPedidos(string origen, string destino)
        {
            var origenParameter = origen != null ?
                new ObjectParameter("origen", origen) :
                new ObjectParameter("origen", typeof(string));
    
            var destinoParameter = destino != null ?
                new ObjectParameter("destino", destino) :
                new ObjectParameter("destino", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_TrasladoPedidos", origenParameter, destinoParameter);
        }
    
        public virtual int SP_TrasladoRecibos(string origen, string destino)
        {
            var origenParameter = origen != null ?
                new ObjectParameter("origen", origen) :
                new ObjectParameter("origen", typeof(string));
    
            var destinoParameter = destino != null ?
                new ObjectParameter("destino", destino) :
                new ObjectParameter("destino", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_TrasladoRecibos", origenParameter, destinoParameter);
        }
    
        public virtual ObjectResult<SP_InventarioXColeccion_Result> SP_InventarioXColeccion(Nullable<int> idColeccion)
        {
            var idColeccionParameter = idColeccion.HasValue ?
                new ObjectParameter("idColeccion", idColeccion) :
                new ObjectParameter("idColeccion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_InventarioXColeccion_Result>("SP_InventarioXColeccion", idColeccionParameter);
        }
    
        public virtual int SP_LimpiarAsignacionesAsesor(string asesor)
        {
            var asesorParameter = asesor != null ?
                new ObjectParameter("asesor", asesor) :
                new ObjectParameter("asesor", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_LimpiarAsignacionesAsesor", asesorParameter);
        }
    
        public virtual ObjectResult<SP_DocumentosAplicadosXCuotas_Result> SP_DocumentosAplicadosXCuotas(string codigoAsesor)
        {
            var codigoAsesorParameter = codigoAsesor != null ?
                new ObjectParameter("CodigoAsesor", codigoAsesor) :
                new ObjectParameter("CodigoAsesor", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DocumentosAplicadosXCuotas_Result>("SP_DocumentosAplicadosXCuotas", codigoAsesorParameter);
        }
    
        public virtual int SP_ActualizarFleteFacturasAcuerdo(string cLIENTE)
        {
            var cLIENTEParameter = cLIENTE != null ?
                new ObjectParameter("CLIENTE", cLIENTE) :
                new ObjectParameter("CLIENTE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ActualizarFleteFacturasAcuerdo", cLIENTEParameter);
        }
    
        public virtual ObjectResult<SPObtenerTiemposFueraDelDia_Result> SPObtenerTiemposFueraDelDia(string asesor)
        {
            var asesorParameter = asesor != null ?
                new ObjectParameter("asesor", asesor) :
                new ObjectParameter("asesor", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPObtenerTiemposFueraDelDia_Result>("SPObtenerTiemposFueraDelDia", asesorParameter);
        }
    
        public virtual int SPActualizarSubFacturasCuotaCero()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SPActualizarSubFacturasCuotaCero");
        }
    
        public virtual ObjectResult<SPObtenerSaldoCuotaCero_Result> SPObtenerSaldoCuotaCero()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPObtenerSaldoCuotaCero_Result>("SPObtenerSaldoCuotaCero");
        }
    
        public virtual ObjectResult<Nullable<decimal>> IMObtenerPagadoCuota(string aCUERDO, Nullable<int> cUOTA)
        {
            var aCUERDOParameter = aCUERDO != null ?
                new ObjectParameter("ACUERDO", aCUERDO) :
                new ObjectParameter("ACUERDO", typeof(string));
    
            var cUOTAParameter = cUOTA.HasValue ?
                new ObjectParameter("CUOTA", cUOTA) :
                new ObjectParameter("CUOTA", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("IMObtenerPagadoCuota", aCUERDOParameter, cUOTAParameter);
        }
    
        public virtual ObjectResult<IMObtenerDetalleDescuento_Result> IMObtenerDetalleDescuento(string eMPRESA, string lINEA, string cODIGO)
        {
            var eMPRESAParameter = eMPRESA != null ?
                new ObjectParameter("EMPRESA", eMPRESA) :
                new ObjectParameter("EMPRESA", typeof(string));
    
            var lINEAParameter = lINEA != null ?
                new ObjectParameter("LINEA", lINEA) :
                new ObjectParameter("LINEA", typeof(string));
    
            var cODIGOParameter = cODIGO != null ?
                new ObjectParameter("CODIGO", cODIGO) :
                new ObjectParameter("CODIGO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IMObtenerDetalleDescuento_Result>("IMObtenerDetalleDescuento", eMPRESAParameter, lINEAParameter, cODIGOParameter);
        }
    
        public virtual ObjectResult<IMObtenerFacturasFletes_Result> IMObtenerFacturasFletes(string codigoCliente)
        {
            var codigoClienteParameter = codigoCliente != null ?
                new ObjectParameter("CodigoCliente", codigoCliente) :
                new ObjectParameter("CodigoCliente", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IMObtenerFacturasFletes_Result>("IMObtenerFacturasFletes", codigoClienteParameter);
        }
    
        public virtual ObjectResult<IMObtenerProductosColeccionConInventario_Result> IMObtenerProductosColeccionConInventario(string empresa, string coleccion)
        {
            var empresaParameter = empresa != null ?
                new ObjectParameter("empresa", empresa) :
                new ObjectParameter("empresa", typeof(string));
    
            var coleccionParameter = coleccion != null ?
                new ObjectParameter("coleccion", coleccion) :
                new ObjectParameter("coleccion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IMObtenerProductosColeccionConInventario_Result>("IMObtenerProductosColeccionConInventario", empresaParameter, coleccionParameter);
        }
    
        public virtual ObjectResult<IMClasificacionDevolucion_Result> IMClasificacionDevolucion(string numdevolucion)
        {
            var numdevolucionParameter = numdevolucion != null ?
                new ObjectParameter("numdevolucion", numdevolucion) :
                new ObjectParameter("numdevolucion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IMClasificacionDevolucion_Result>("IMClasificacionDevolucion", numdevolucionParameter);
        }
    
        public virtual ObjectResult<IMObtenerBasesProductos_Result> IMObtenerBasesProductos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IMObtenerBasesProductos_Result>("IMObtenerBasesProductos");
        }
    
        public virtual ObjectResult<IMObtenerFacturasDevolucionCompleta_Result> IMObtenerFacturasDevolucionCompleta(string cLIENTE)
        {
            var cLIENTEParameter = cLIENTE != null ?
                new ObjectParameter("CLIENTE", cLIENTE) :
                new ObjectParameter("CLIENTE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IMObtenerFacturasDevolucionCompleta_Result>("IMObtenerFacturasDevolucionCompleta", cLIENTEParameter);
        }
    
        public virtual int SP_LimpiarInventarioFactura(string fACTURA)
        {
            var fACTURAParameter = fACTURA != null ?
                new ObjectParameter("FACTURA", fACTURA) :
                new ObjectParameter("FACTURA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_LimpiarInventarioFactura", fACTURAParameter);
        }
    
        public virtual int SP_Devoluciones_UpdateEstado(string codigoAsesor)
        {
            var codigoAsesorParameter = codigoAsesor != null ?
                new ObjectParameter("codigoAsesor", codigoAsesor) :
                new ObjectParameter("codigoAsesor", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Devoluciones_UpdateEstado", codigoAsesorParameter);
        }
    
        public virtual int SP_DocumentosTransitoxFactura_UpdateSaldo(string aSESOR)
        {
            var aSESORParameter = aSESOR != null ?
                new ObjectParameter("ASESOR", aSESOR) :
                new ObjectParameter("ASESOR", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DocumentosTransitoxFactura_UpdateSaldo", aSESORParameter);
        }
    
        public virtual int IMActualizarColeccionInventarioEspecifico(string cOLECCION, Nullable<int> aCTIVAR)
        {
            var cOLECCIONParameter = cOLECCION != null ?
                new ObjectParameter("COLECCION", cOLECCION) :
                new ObjectParameter("COLECCION", typeof(string));
    
            var aCTIVARParameter = aCTIVAR.HasValue ?
                new ObjectParameter("ACTIVAR", aCTIVAR) :
                new ObjectParameter("ACTIVAR", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("IMActualizarColeccionInventarioEspecifico", cOLECCIONParameter, aCTIVARParameter);
        }
    
        public virtual ObjectResult<IMObtenerColeccionesInventarioEspecifico_Result> IMObtenerColeccionesInventarioEspecifico()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IMObtenerColeccionesInventarioEspecifico_Result>("IMObtenerColeccionesInventarioEspecifico");
        }
    
        public virtual ObjectResult<SP_ObtenerInventarioIncompleto_Result> SP_ObtenerInventarioIncompleto(string cliente)
        {
            var clienteParameter = cliente != null ?
                new ObjectParameter("cliente", cliente) :
                new ObjectParameter("cliente", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ObtenerInventarioIncompleto_Result>("SP_ObtenerInventarioIncompleto", clienteParameter);
        }
    
        public virtual ObjectResult<SP_ObtenerInventario_Result> SP_ObtenerInventario(string cliente)
        {
            var clienteParameter = cliente != null ?
                new ObjectParameter("cliente", cliente) :
                new ObjectParameter("cliente", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ObtenerInventario_Result>("SP_ObtenerInventario", clienteParameter);
        }
    
        public virtual int IMEliminarAsignacionesRangoFecha(string asesor, string inicio, string fin)
        {
            var asesorParameter = asesor != null ?
                new ObjectParameter("asesor", asesor) :
                new ObjectParameter("asesor", typeof(string));
    
            var inicioParameter = inicio != null ?
                new ObjectParameter("inicio", inicio) :
                new ObjectParameter("inicio", typeof(string));
    
            var finParameter = fin != null ?
                new ObjectParameter("fin", fin) :
                new ObjectParameter("fin", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("IMEliminarAsignacionesRangoFecha", asesorParameter, inicioParameter, finParameter);
        }
    
        public virtual ObjectResult<SP_ReservadoClienteColeccionesLineas_Result> SP_ReservadoClienteColeccionesLineas(string cLIENTE, string lINEA)
        {
            var cLIENTEParameter = cLIENTE != null ?
                new ObjectParameter("CLIENTE", cLIENTE) :
                new ObjectParameter("CLIENTE", typeof(string));
    
            var lINEAParameter = lINEA != null ?
                new ObjectParameter("LINEA", lINEA) :
                new ObjectParameter("LINEA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ReservadoClienteColeccionesLineas_Result>("SP_ReservadoClienteColeccionesLineas", cLIENTEParameter, lINEAParameter);
        }
    
        public virtual ObjectResult<SP_ReservadoClientePorLinea_Result> SP_ReservadoClientePorLinea(string cLIENTE)
        {
            var cLIENTEParameter = cLIENTE != null ?
                new ObjectParameter("CLIENTE", cLIENTE) :
                new ObjectParameter("CLIENTE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ReservadoClientePorLinea_Result>("SP_ReservadoClientePorLinea", cLIENTEParameter);
        }
    
        public virtual int IMReestablecerUnidadesDevolucion(string devolucion)
        {
            var devolucionParameter = devolucion != null ?
                new ObjectParameter("Devolucion", devolucion) :
                new ObjectParameter("Devolucion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("IMReestablecerUnidadesDevolucion", devolucionParameter);
        }
    
        public virtual ObjectResult<SP_ObtenerFacturasAbiertas_Result1> SP_ObtenerFacturasAbiertas(string cliente)
        {
            var clienteParameter = cliente != null ?
                new ObjectParameter("cliente", cliente) :
                new ObjectParameter("cliente", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ObtenerFacturasAbiertas_Result1>("SP_ObtenerFacturasAbiertas", clienteParameter);
        }
    
        public virtual int SPDesactivarDireccionesCliente(string cLIENTE)
        {
            var cLIENTEParameter = cLIENTE != null ?
                new ObjectParameter("CLIENTE", cLIENTE) :
                new ObjectParameter("CLIENTE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SPDesactivarDireccionesCliente", cLIENTEParameter);
        }
    }
}
