//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class AVentasEntities : DbContext
    {
        public AVentasEntities()
            : base("name=AVentasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AcuerdosxCliente> AcuerdosxCliente { get; set; }
        public virtual DbSet<AcuerdosxClienteDetalle> AcuerdosxClienteDetalle { get; set; }
        public virtual DbSet<Asesores> Asesores { get; set; }
        public virtual DbSet<AsignacionxAsesor> AsignacionxAsesor { get; set; }
        public virtual DbSet<AsignacionxAsesorDetalle> AsignacionxAsesorDetalle { get; set; }
        public virtual DbSet<AtributosxColeccion> AtributosxColeccion { get; set; }
        public virtual DbSet<AtributosxProducto> AtributosxProducto { get; set; }
        public virtual DbSet<Bancos> Bancos { get; set; }
        public virtual DbSet<BitacoraGeoposicion> BitacoraGeoposicion { get; set; }
        public virtual DbSet<BitacoraVisitasCliente> BitacoraVisitasCliente { get; set; }
        public virtual DbSet<Clientes> Clientes { get; set; }
        public virtual DbSet<ClientesxRuta> ClientesxRuta { get; set; }
        public virtual DbSet<Colecciones> Colecciones { get; set; }
        public virtual DbSet<Colores> Colores { get; set; }
        public virtual DbSet<ColoresxProducto> ColoresxProducto { get; set; }
        public virtual DbSet<Configuraciones> Configuraciones { get; set; }
        public virtual DbSet<CuentasBancarias> CuentasBancarias { get; set; }
        public virtual DbSet<DistribucionxTalla> DistribucionxTalla { get; set; }
        public virtual DbSet<EdadesxColeccion> EdadesxColeccion { get; set; }
        public virtual DbSet<Empresa> Empresa { get; set; }
        public virtual DbSet<Errores> Errores { get; set; }
        public virtual DbSet<EstadosPedido> EstadosPedido { get; set; }
        public virtual DbSet<FacturasxCliente> FacturasxCliente { get; set; }
        public virtual DbSet<FirmasxPedido> FirmasxPedido { get; set; }
        public virtual DbSet<FormularioIntroDetalle> FormularioIntroDetalle { get; set; }
        public virtual DbSet<FormularioIntroDetallexRoles> FormularioIntroDetallexRoles { get; set; }
        public virtual DbSet<FormularioIntroEncabezado> FormularioIntroEncabezado { get; set; }
        public virtual DbSet<GrupoTalla> GrupoTalla { get; set; }
        public virtual DbSet<LimiteCreditoxCliente> LimiteCreditoxCliente { get; set; }
        public virtual DbSet<LineasxColeccion> LineasxColeccion { get; set; }
        public virtual DbSet<MaestroEdad> MaestroEdad { get; set; }
        public virtual DbSet<MaestroGrupoPrecio> MaestroGrupoPrecio { get; set; }
        public virtual DbSet<MaestroLinea> MaestroLinea { get; set; }
        public virtual DbSet<MaestroMoneda> MaestroMoneda { get; set; }
        public virtual DbSet<MonedasxEmpresa> MonedasxEmpresa { get; set; }
        public virtual DbSet<PrioridadAsignacion> PrioridadAsignacion { get; set; }
        public virtual DbSet<ProductosxColeccion> ProductosxColeccion { get; set; }
        public virtual DbSet<RazonNoVentaCausa> RazonNoVentaCausa { get; set; }
        public virtual DbSet<RazonNoVentaTipo> RazonNoVentaTipo { get; set; }
        public virtual DbSet<RecibosDetalle> RecibosDetalle { get; set; }
        public virtual DbSet<Rutas> Rutas { get; set; }
        public virtual DbSet<RutasxAsesor> RutasxAsesor { get; set; }
        public virtual DbSet<SubFacturasxCliente> SubFacturasxCliente { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TallasXGrupo> TallasXGrupo { get; set; }
        public virtual DbSet<TallasxProducto> TallasxProducto { get; set; }
        public virtual DbSet<TiposdeColeccion> TiposdeColeccion { get; set; }
        public virtual DbSet<TiposdePago> TiposdePago { get; set; }
        public virtual DbSet<TiposdePagoDetalle> TiposdePagoDetalle { get; set; }
        public virtual DbSet<TiposdePedido> TiposdePedido { get; set; }
        public virtual DbSet<TipoVisitaCliente> TipoVisitaCliente { get; set; }
        public virtual DbSet<Acciones> Acciones { get; set; }
        public virtual DbSet<vw_AtributosxColeccion> vw_AtributosxColeccion { get; set; }
        public virtual DbSet<vw_ClientesxRuta> vw_ClientesxRuta { get; set; }
        public virtual DbSet<vw_ColoresxProducto> vw_ColoresxProducto { get; set; }
        public virtual DbSet<vw_FisicoDisponible> vw_FisicoDisponible { get; set; }
        public virtual DbSet<vw_TallasxProducto> vw_TallasxProducto { get; set; }
        public virtual DbSet<AnticiposxCliente> AnticiposxCliente { get; set; }
        public virtual DbSet<RecibosxCliente> RecibosxCliente { get; set; }
        public virtual DbSet<GrupoImpuestoArticulo> GrupoImpuestoArticulo { get; set; }
        public virtual DbSet<GrupoImpuestoCliente> GrupoImpuestoCliente { get; set; }
        public virtual DbSet<PedidosxCliente> PedidosxCliente { get; set; }
        public virtual DbSet<ComunidadAutonoma> ComunidadAutonoma { get; set; }
        public virtual DbSet<EmpresaTransporte> EmpresaTransporte { get; set; }
        public virtual DbSet<TransportePrecioCaja> TransportePrecioCaja { get; set; }
        public virtual DbSet<PreciosxProducto> PreciosxProducto { get; set; }
        public virtual DbSet<FisicoDisponible> FisicoDisponible { get; set; }
        public virtual DbSet<FotografiasXProducto> FotografiasXProducto { get; set; }
        public virtual DbSet<PrecioEspecifico> PrecioEspecifico { get; set; }
        public virtual DbSet<ClienteContado> ClienteContado { get; set; }
        public virtual DbSet<PedidosDetalle> PedidosDetalle { get; set; }
        public virtual DbSet<Funciones> Funciones { get; set; }
        public virtual DbSet<Funciones_Roles> Funciones_Roles { get; set; }
        public virtual DbSet<Pantallas> Pantallas { get; set; }
        public virtual DbSet<Pantallas_Funciones> Pantallas_Funciones { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<PantallasxUsuario> PantallasxUsuario { get; set; }
        public virtual DbSet<Usuario_Rol> Usuario_Rol { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
        public virtual DbSet<Usuarios_Empresas> Usuarios_Empresas { get; set; }
        public virtual DbSet<Usuarios_Asesores> Usuarios_Asesores { get; set; }
    
        public virtual ObjectResult<CuentaCorriente_Result> CuentaCorriente(string codigoCliente)
        {
            var codigoClienteParameter = codigoCliente != null ?
                new ObjectParameter("CodigoCliente", codigoCliente) :
                new ObjectParameter("CodigoCliente", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CuentaCorriente_Result>("CuentaCorriente", codigoClienteParameter);
        }
    
        public virtual ObjectResult<CuentaCorriente2_Result> CuentaCorriente2(string codigoCliente)
        {
            var codigoClienteParameter = codigoCliente != null ?
                new ObjectParameter("CodigoCliente", codigoCliente) :
                new ObjectParameter("CodigoCliente", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CuentaCorriente2_Result>("CuentaCorriente2", codigoClienteParameter);
        }
    
        public virtual ObjectResult<EstadisticaVisita_Result> EstadisticaVisita(Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFin, string user)
        {
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("FechaInicio", fechaInicio) :
                new ObjectParameter("FechaInicio", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("FechaFin", fechaFin) :
                new ObjectParameter("FechaFin", typeof(System.DateTime));
    
            var userParameter = user != null ?
                new ObjectParameter("User", user) :
                new ObjectParameter("User", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EstadisticaVisita_Result>("EstadisticaVisita", fechaInicioParameter, fechaFinParameter, userParameter);
        }
    
        public virtual ObjectResult<PResumenCredito_Result> PResumenCredito()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PResumenCredito_Result>("PResumenCredito");
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual ObjectResult<SP_VISITASPORMES_Result> SP_VISITASPORMES()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_VISITASPORMES_Result>("SP_VISITASPORMES");
        }
    }
}
