//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaseColorImpuesto
    {
        public int id { get; set; }
        public string codigobase { get; set; }
        public string color { get; set; }
        public decimal porcentajeImpuesto { get; set; }
        public string empresa { get; set; }
        public bool activo { get; set; }
        public System.DateTime fechaCreacion { get; set; }
        public System.DateTime fechaModificacion { get; set; }
        public string usuario { get; set; }
        public string codigoimpuesto { get; set; }
    }
}
