//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class BitacoraNoVentaEnVisitas
    {
        public int IdNoVentaEnVisita { get; set; }
        public int IdRazonNoVenta { get; set; }
        public int IdAsignacionXAsesor { get; set; }
        public string Comentarios { get; set; }
        public Nullable<System.DateTime> FechaCrea { get; set; }
        public Nullable<int> UsuarioCrea { get; set; }
    
        public virtual AsignacionxAsesor AsignacionxAsesor { get; set; }
        public virtual RazonesNoVenta RazonesNoVenta { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
