//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class BitacoraVisitasCliente
    {
        public int IdBitacoraVisitaCliente { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> IdRazonNoVentaTipo { get; set; }
        public Nullable<int> IdRazonNoVentaCausa { get; set; }
        public string CodigoCliente { get; set; }
        public string CodigoAsesor { get; set; }
        public Nullable<int> IdAsignacionxAsesor { get; set; }
        public string Observacion { get; set; }
    
        public virtual Asesores Asesores { get; set; }
        public virtual Clientes Clientes { get; set; }
        public virtual RazonNoVentaTipo RazonNoVentaTipo { get; set; }
        public virtual RazonNoVentaCausa RazonNoVentaCausa { get; set; }
    }
}
