//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class BitacoraGeoposicion
    {
        public int IdBitacoraGeo { get; set; }
        public Nullable<int> IdAsignacionxAsesor { get; set; }
        public Nullable<bool> Mocked { get; set; }
        public Nullable<decimal> Accuracy { get; set; }
        public Nullable<decimal> Altitude { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public string CodigoAsesor { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string CodigoCliente { get; set; }
    
        public virtual Asesores Asesores { get; set; }
        public virtual AsignacionxAsesor AsignacionxAsesor { get; set; }
        public virtual Clientes Clientes { get; set; }
    }
}
