//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class BitacoraVisitasCliente
    {
        public int IdBitacoraVisitaCliente { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> IdRazonNoVentaTipo { get; set; }
        public Nullable<int> IdRazonNoVentaCausa { get; set; }
        public string CodigoCliente { get; set; }
        public string CodigoAsesor { get; set; }
        public Nullable<int> IdAsignacionxAsesor { get; set; }
        public string Observacion { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual RazonNoVentaTipo RazonNoVentaTipo { get; set; }
        public virtual RazonNoVentaCausa RazonNoVentaCausa { get; set; }
    }
}
