//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class BitacoraGeoposicion
    {
        public int IdBitacoraGeo { get; set; }
        public Nullable<int> IdAsignacionxAsesor { get; set; }
        public Nullable<bool> Mocked { get; set; }
        public Nullable<decimal> Accuracy { get; set; }
        public Nullable<decimal> Altitude { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public string CodigoAsesor { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string CodigoCliente { get; set; }
    
        public virtual Asesores Asesores { get; set; }
        public virtual AsignacionxAsesor AsignacionxAsesor { get; set; }
        public virtual Clientes Clientes { get; set; }
    }
}
