//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoriaTipoGastoViaje
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CategoriaTipoGastoViaje()
        {
            this.GastosViajeDetalle = new HashSet<GastosViajeDetalle>();
        }
    
        public int IdCategoriaTipoGastoViaje { get; set; }
        public int IdTipoGastoViaje { get; set; }
        public string Nombre { get; set; }
        public bool FacturaObligatoria { get; set; }
        public bool Descripcion { get; set; }
        public bool ImagenObligatoria { get; set; }
        public bool Activo { get; set; }
        public string ProveedorPredefinido { get; set; }
        public string CuentaContrapartida { get; set; }
        public string GrupoImpuesto { get; set; }
    
        public virtual TipoGastoViaje TipoGastoViaje { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GastosViajeDetalle> GastosViajeDetalle { get; set; }
    }
}
