//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChequesContabilizados
    {
        public int Id { get; set; }
        public string NumeroRecibo { get; set; }
        public System.DateTime FechaRecepcion { get; set; }
        public string NumeroCheque { get; set; }
        public string Banco { get; set; }
        public decimal ValorCheque { get; set; }
        public System.DateTime FechaVencimiento { get; set; }
        public string TipoCheque { get; set; }
        public string CodigoCliente { get; set; }
        public bool Activo { get; set; }
    }
}
