//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChequesContabilizados
    {
        public int Id { get; set; }
        public string NumeroRecibo { get; set; }
        public System.DateTime FechaRecepcion { get; set; }
        public string NumeroCheque { get; set; }
        public string Banco { get; set; }
        public decimal ValorCheque { get; set; }
        public System.DateTime FechaVencimiento { get; set; }
        public string TipoCheque { get; set; }
        public string CodigoCliente { get; set; }
        public bool Activo { get; set; }
    }
}
