//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClasificacionDevolucion
    {
        public int id { get; set; }
        public string numdevolucion { get; set; }
        public string codigoColor { get; set; }
        public string codigoTalla { get; set; }
        public Nullable<int> cantidadMantenimiento { get; set; }
        public string clasificacion { get; set; }
        public Nullable<int> operacionId { get; set; }
        public Nullable<int> defectoId { get; set; }
        public Nullable<int> idProducto { get; set; }
    }
}
