//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClasificacionDevolucion
    {
        public int id { get; set; }
        public string numdevolucion { get; set; }
        public string codigoColor { get; set; }
        public string codigoTalla { get; set; }
        public Nullable<int> cantidadMantenimiento { get; set; }
        public string clasificacion { get; set; }
        public Nullable<int> operacionId { get; set; }
        public Nullable<int> defectoId { get; set; }
        public Nullable<int> idProducto { get; set; }
    }
}
