//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientesxRuta
    {
        public int IdClientexRuta { get; set; }
        public string CodigoRuta { get; set; }
        public string CodigoCliente { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Rutas Rutas { get; set; }
    }
}
