//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clientes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Clientes()
        {
            this.AcuerdosxCliente = new HashSet<AcuerdosxCliente>();
            this.ClientesxRuta = new HashSet<ClientesxRuta>();
            this.FacturasxCliente = new HashSet<FacturasxCliente>();
            this.LimiteCreditoxCliente = new HashSet<LimiteCreditoxCliente>();
            this.SubFacturasxCliente = new HashSet<SubFacturasxCliente>();
            this.Respuestas = new HashSet<Respuestas>();
            this.DocumentosTransitoxFactura = new HashSet<DocumentosTransitoxFactura>();
            this.AsignacionxAsesor = new HashSet<AsignacionxAsesor>();
            this.BitacoraGeoposicion = new HashSet<BitacoraGeoposicion>();
            this.BitacoraVisitasCliente = new HashSet<BitacoraVisitasCliente>();
            this.PedidosxCliente = new HashSet<PedidosxCliente>();
            this.PedidosxClienteFlotante = new HashSet<PedidosxClienteFlotante>();
            this.Devolucion = new HashSet<Devolucion>();
        }
    
        public string CodigoCliente { get; set; }
        public string EmpresaId { get; set; }
        public string Nombre { get; set; }
        public string Zona { get; set; }
        public string ComunidadAutonoma { get; set; }
        public string GrupoPrecio { get; set; }
        public string GrupoCliente { get; set; }
        public string Descuento { get; set; }
        public string Direccion { get; set; }
        public string IdMoneda { get; set; }
        public string FacturacionEntrega { get; set; }
        public Nullable<decimal> Latitud { get; set; }
        public Nullable<decimal> Longitud { get; set; }
        public string Provincias { get; set; }
        public string Region { get; set; }
        public Nullable<bool> Revision { get; set; }
        public Nullable<decimal> LimiteCredito { get; set; }
        public Nullable<decimal> CreditoDisponible { get; set; }
        public string Telefono { get; set; }
        public string GrupoImpuesto { get; set; }
        public string ModoEntrega { get; set; }
        public string CodigoAsesor { get; set; }
        public bool Habilitado { get; set; }
        public byte[] VersionRegistro { get; set; }
        public Nullable<long> VersionRegistroBINT { get; set; }
        public Nullable<bool> IgnorarSeqFact { get; set; }
        public Nullable<bool> IncluyeImpuesto { get; set; }
        public bool FlagClienteEspecial { get; set; }
        public int DiasTransporte { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AcuerdosxCliente> AcuerdosxCliente { get; set; }
        public virtual MaestroGrupoPrecio MaestroGrupoPrecio { get; set; }
        public virtual MaestroMoneda MaestroMoneda { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientesxRuta> ClientesxRuta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FacturasxCliente> FacturasxCliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LimiteCreditoxCliente> LimiteCreditoxCliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubFacturasxCliente> SubFacturasxCliente { get; set; }
        public virtual Empresa Empresa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Respuestas> Respuestas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentosTransitoxFactura> DocumentosTransitoxFactura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AsignacionxAsesor> AsignacionxAsesor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BitacoraGeoposicion> BitacoraGeoposicion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BitacoraVisitasCliente> BitacoraVisitasCliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PedidosxCliente> PedidosxCliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PedidosxClienteFlotante> PedidosxClienteFlotante { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Devolucion> Devolucion { get; set; }
    }
}
