//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClienteContado
    {
        public int id { get; set; }
        public string Nombre { get; set; }
        public string Direccion { get; set; }
        public string RTN { get; set; }
        public Nullable<bool> FlagClientePotencial { get; set; }
        public string Telefono { get; set; }
        public string ComunidadAutonoma { get; set; }
        public string Ruta { get; set; }
    }
}
