//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Colecciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Colecciones()
        {
            this.AtributosxColeccion = new HashSet<AtributosxColeccion>();
            this.EdadesxColeccion = new HashSet<EdadesxColeccion>();
            this.LineasxColeccion = new HashSet<LineasxColeccion>();
            this.ProductosxColeccion = new HashSet<ProductosxColeccion>();
            this.ListasPreciosPaquetes = new HashSet<ListasPreciosPaquetes>();
            this.PaqueteBodegaEspecifico = new HashSet<PaqueteBodegaEspecifico>();
            this.PedidosxCliente = new HashSet<PedidosxCliente>();
            this.PedidosxClienteFlotante = new HashSet<PedidosxClienteFlotante>();
        }
    
        public int IdColeccion { get; set; }
        public string CodigoColeccion { get; set; }
        public string Nombre { get; set; }
        public string ColeccionTipo { get; set; }
        public string EmpresaId { get; set; }
        public Nullable<System.DateTime> DisenoInicio { get; set; }
        public Nullable<System.DateTime> DisenoFinal { get; set; }
        public Nullable<System.DateTime> EntregaInicio { get; set; }
        public Nullable<System.DateTime> EntregaFinal { get; set; }
        public Nullable<int> Estatus { get; set; }
        public Nullable<System.DateTime> ProduccionInicio { get; set; }
        public Nullable<System.DateTime> ProduccionFinal { get; set; }
        public Nullable<System.DateTime> VentaInicio { get; set; }
        public Nullable<System.DateTime> VentaFinal { get; set; }
        public string FotoPortada { get; set; }
        public Nullable<System.DateTime> FechaUltSincronizacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AtributosxColeccion> AtributosxColeccion { get; set; }
        public virtual TiposdeColeccion TiposdeColeccion { get; set; }
        public virtual Empresa Empresa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EdadesxColeccion> EdadesxColeccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LineasxColeccion> LineasxColeccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductosxColeccion> ProductosxColeccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ListasPreciosPaquetes> ListasPreciosPaquetes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaqueteBodegaEspecifico> PaqueteBodegaEspecifico { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PedidosxCliente> PedidosxCliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PedidosxClienteFlotante> PedidosxClienteFlotante { get; set; }
    }
}
