//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ColoresxProducto
    {
        public int IdColorxProducto { get; set; }
        public string CodigoColor { get; set; }
        public Nullable<int> IdProducto { get; set; }
        public Nullable<bool> Disponible { get; set; }
        public int Prioridad { get; set; }
        public bool Deshabilitado { get; set; }
    
        public virtual Colores Colores { get; set; }
        public virtual ProductosxColeccion ProductosxColeccion { get; set; }
    }
}
