//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ColoresxProducto
    {
        public int IdColorxProducto { get; set; }
        public string CodigoColor { get; set; }
        public Nullable<int> IdProducto { get; set; }
        public Nullable<bool> Disponible { get; set; }
    
        public virtual Colores Colores { get; set; }
        public virtual ProductosxColeccion ProductosxColeccion { get; set; }
    }
}
