//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;

    public partial class ConfiguracionCorreo
    {
        public int Id { get; set; }
        public string EmpresaId { get; set; }
        public int TipoConfiguracionId { get; set; }
        public string CorreosDestino { get; set; }
        public string CorreosCopia { get; set; }
        public string Asunto { get; set; }
        public string CuerpoPlantilla { get; set; }
        public bool Activo { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string UsuarioCreacion { get; set; }
        public string UsuarioModifico { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }

        public virtual Empresa Empresa { get; set; }
        public virtual TipoConfiguracionCorreo TipoConfiguracionCorreo { get; set; }
    }
}
