//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONFIGURACIONE
    {
        public int CODIGO { get; set; }
        public string VALOR { get; set; }
        public string DESCRIPCION { get; set; }
        public string MODULO { get; set; }
        public System.Guid ROWID { get; set; }
    }
}
