//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactoServicio
    {
        public int Id { get; set; }
        public string IdEmpresa { get; set; }
        public string Telefono { get; set; }
        public string Whatsapp { get; set; }
        public string UrlQRWhatsapp { get; set; }
        public Nullable<int> IdServicio { get; set; }
        public bool Activo { get; set; }
    
        public virtual Servicio Servicio { get; set; }
    }
}
