//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuentasBancarias
    {
        public int IdCuentaBancaria { get; set; }
        public string NombreBanco { get; set; }
        public string NumeroCuenta { get; set; }
        public string Descripcion { get; set; }
        public string GrupoBanco { get; set; }
        public Nullable<int> IdBanco { get; set; }
        public string IdMoneda { get; set; }
        public string EmpresaId { get; set; }
    
        public virtual Bancos Bancos { get; set; }
        public virtual Empresa Empresa { get; set; }
        public virtual MaestroMoneda MaestroMoneda { get; set; }
    }
}
