//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuotasXAcuerdo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CuotasXAcuerdo()
        {
            this.FacturasEnCuotasAcuerdos = new HashSet<FacturasEnCuotasAcuerdos>();
        }
    
        public int IdCuotasXAcuerdoVenta { get; set; }
        public string IdAcuerdoVenta { get; set; }
        public int NumCuota { get; set; }
        public decimal ValorCuota { get; set; }
        public Nullable<decimal> SaldoDiponible { get; set; }
        public Nullable<System.DateTime> FechaVencimiento { get; set; }
    
        public virtual AcuerdosxCliente AcuerdosxCliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FacturasEnCuotasAcuerdos> FacturasEnCuotasAcuerdos { get; set; }
    }
}
