//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepositoRecibo
    {
        public int id { get; set; }
        public Nullable<int> reciboId { get; set; }
        public string depositoUrl { get; set; }
    
        public virtual RecibosxCliente RecibosxCliente { get; set; }
    }
}
