//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class DescuentoEnAcuerdo
    {
        public int IdDescuentoAcuerdo { get; set; }
        public string CodigoDescuento { get; set; }
        public string Descripcion { get; set; }
        public decimal Porcentaje { get; set; }
        public int Dias { get; set; }
        public string empresaId { get; set; }
    
        public virtual Empresa Empresa { get; set; }
    }
}
