//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class DescuentoEnAcuerdo
    {
        public int IdDescuentoAcuerdo { get; set; }
        public string CodigoDescuento { get; set; }
        public string Descripcion { get; set; }
        public decimal Porcentaje { get; set; }
        public int Dias { get; set; }
        public string empresaId { get; set; }
    
        public virtual Empresa Empresa { get; set; }
    }
}
