//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class DescuentoDetalle
    {
        public int IdDescuentoDetalle { get; set; }
        public int IdDescuento { get; set; }
        public string IdLinea { get; set; }
        public string CodigoDescuento { get; set; }
        public Nullable<int> DiasDescuento { get; set; }
        public Nullable<decimal> Porcentaje { get; set; }
        public bool activo { get; set; }
    
        public virtual Descuento Descuento { get; set; }
        public virtual MaestroLinea MaestroLinea { get; set; }
    }
}
