//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleFacturado
    {
        public int id { get; set; }
        public Nullable<int> productoId { get; set; }
        public string codigoProducto { get; set; }
        public string codigoColor { get; set; }
        public string codigoTalla { get; set; }
        public Nullable<decimal> cantidad { get; set; }
        public Nullable<decimal> precioFacturado { get; set; }
        public string factura { get; set; }
        public string pedido { get; set; }
        public string paquete { get; set; }
        public string inventdim { get; set; }
    }
}
