//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleFacturado
    {
        public int id { get; set; }
        public Nullable<int> productoId { get; set; }
        public string codigoProducto { get; set; }
        public string codigoColor { get; set; }
        public string codigoTalla { get; set; }
        public Nullable<decimal> cantidad { get; set; }
        public Nullable<decimal> precioFacturado { get; set; }
        public string factura { get; set; }
        public string pedido { get; set; }
    }
}
