//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Devolucion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Devolucion()
        {
            this.DevolucionDetalle = new HashSet<DevolucionDetalle>();
            this.AprobacionDevoluciones = new HashSet<AprobacionDevoluciones>();
        }
    
        public string NumDevolucion { get; set; }
        public string PedidoDevolucion { get; set; }
        public string NumeroRMA { get; set; }
        public string CodigoCliente { get; set; }
        public string IdLinea { get; set; }
        public int IdMotivoDevDetalle { get; set; }
        public string EmpresaId { get; set; }
        public string Observacion { get; set; }
        public string CodigoAsesor { get; set; }
        public string Estado { get; set; }
        public bool Procesando { get; set; }
        public string ErrorAx { get; set; }
        public Nullable<int> UsuarioCrea { get; set; }
        public Nullable<System.DateTime> FechaCrea { get; set; }
        public string PedidoOrigen { get; set; }
        public string FacturaOrigen { get; set; }
        public bool Sincronizado { get; set; }
        public Nullable<int> TotalUnidades { get; set; }
        public Nullable<decimal> Subtotal { get; set; }
        public string almacen { get; set; }
        public Nullable<int> IdUbicacion { get; set; }
        public Nullable<int> EstadoBodega { get; set; }
        public string Origen { get; set; }
        public Nullable<System.DateTime> FechaProcesado { get; set; }
        public string NotaCredito { get; set; }
        public Nullable<System.DateTime> FechaNotaCredito { get; set; }
        public Nullable<System.DateTime> FechaCreacionAx { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Empresa Empresa { get; set; }
        public virtual MaestroLinea MaestroLinea { get; set; }
        public virtual MotivosDevolucionDetalle MotivosDevolucionDetalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DevolucionDetalle> DevolucionDetalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AprobacionDevoluciones> AprobacionDevoluciones { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        public virtual UbicacionesXAlmacen UbicacionesXAlmacen { get; set; }
    }
}
