//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class DevolucionDetalle
    {
        public int IdDevolucionDetalle { get; set; }
        public string NumDevolucion { get; set; }
        public int IdProducto { get; set; }
        public string CodigoColor { get; set; }
        public string CodigoTalla { get; set; }
        public int Cantidad { get; set; }
        public Nullable<decimal> PrecioUnitario { get; set; }
        public Nullable<decimal> MontoLinea { get; set; }
        public string Factura { get; set; }
        public string Pedido { get; set; }
        public string Paquete { get; set; }
        public string Inventdim { get; set; }
    
        public virtual Devolucion Devolucion { get; set; }
        public virtual ProductosxColeccion ProductosxColeccion { get; set; }
    }
}
