//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class DevolucionDetalle
    {
        public int IdDevolucionDetalle { get; set; }
        public string NumDevolucion { get; set; }
        public int IdProducto { get; set; }
        public string CodigoColor { get; set; }
        public string CodigoTalla { get; set; }
        public int Cantidad { get; set; }
        public Nullable<decimal> PrecioUnitario { get; set; }
    
        public virtual Devolucion Devolucion { get; set; }
        public virtual ProductosxColeccion ProductosxColeccion { get; set; }
    }
}
