//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class DireccionesCliente
    {
        public int id { get; set; }
        public string codigoCliente { get; set; }
        public long postalAddress { get; set; }
        public string nombreDireccion { get; set; }
        public string direccion { get; set; }
        public bool activo { get; set; }
        public bool principal { get; set; }
        public System.DateTime fechaCreacion { get; set; }
    }
}
