//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class DireccionesCliente
    {
        public int id { get; set; }
        public string codigoCliente { get; set; }
        public long postalAddress { get; set; }
        public string nombreDireccion { get; set; }
        public string direccion { get; set; }
        public bool activo { get; set; }
        public bool principal { get; set; }
        public System.DateTime fechaCreacion { get; set; }
    }
}
