//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class DistribucionxTalla
    {
        public int IdDistribucion { get; set; }
        public Nullable<int> IdTallaxGrupo { get; set; }
        public string NombreDistribucion { get; set; }
        public string NombreTalla { get; set; }
        public string Cantidad { get; set; }
        public Nullable<decimal> Orden { get; set; }
    
        public virtual TallasXGrupo TallasXGrupo { get; set; }
    }
}
