//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentosTransitoxFactura
    {
        public int IdDocumentoTransito { get; set; }
        public Nullable<int> TablaId { get; set; }
        public string Tipo { get; set; }
        public string ReferenciaSubFactura { get; set; }
        public Nullable<decimal> Valor { get; set; }
        public string IdMoneda { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string Referencia { get; set; }
        public string CodigoCliente { get; set; }
        public string Factura { get; set; }
        public string NumeroFEL { get; set; }
        public string NumeroDocumento { get; set; }
        public string Estado { get; set; }
        public string CreadoPor { get; set; }
        public string ReferenciaFacturas { get; set; }
        public string EmpresaId { get; set; }
        public Nullable<int> IdFactura { get; set; }
        public Nullable<int> IdSubFactura { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Empresa Empresa { get; set; }
        public virtual FacturasxCliente FacturasxCliente { get; set; }
        public virtual MaestroMoneda MaestroMoneda { get; set; }
        public virtual SubFacturasxCliente SubFacturasxCliente { get; set; }
    }
}
