//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentosAplicadosAFacturas
    {
        public int Id { get; set; }
        public string CodigoCliente { get; set; }
        public string Factura { get; set; }
        public string Voucher { get; set; }
        public string TipoDocumento { get; set; }
        public string FacturaDocumento { get; set; }
        public Nullable<decimal> Valor { get; set; }
        public Nullable<decimal> MontoPorAplicar { get; set; }
        public string SecuenciaNumerica { get; set; }
        public string Moneda { get; set; }
        public string Empresa { get; set; }
        public Nullable<System.DateTime> FechaCrea { get; set; }
        public Nullable<int> IdSubFactura { get; set; }
    
        public virtual SubFacturasxCliente SubFacturasxCliente { get; set; }
    }
}
