//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentosAplicadosAFacturas
    {
        public int Id { get; set; }
        public string CodigoCliente { get; set; }
        public string Factura { get; set; }
        public string Voucher { get; set; }
        public string TipoDocumento { get; set; }
        public string FacturaDocumento { get; set; }
        public Nullable<decimal> Valor { get; set; }
        public Nullable<decimal> MontoPorAplicar { get; set; }
        public string SecuenciaNumerica { get; set; }
        public string Moneda { get; set; }
        public string Empresa { get; set; }
        public Nullable<System.DateTime> FechaCrea { get; set; }
        public Nullable<int> IdSubFactura { get; set; }
    
        public virtual SubFacturasxCliente SubFacturasxCliente { get; set; }
    }
}
