//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class EdadesxColeccion
    {
        public int IdEdadXColeccion { get; set; }
        public string IdEdad { get; set; }
        public Nullable<int> IdColeccion { get; set; }
        public string IdLinea { get; set; }
    
        public virtual Colecciones Colecciones { get; set; }
        public virtual MaestroEdad MaestroEdad { get; set; }
        public virtual MaestroLinea MaestroLinea { get; set; }
    }
}
