//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class EdadesxColeccion
    {
        public int IdEdadXColeccion { get; set; }
        public string IdEdad { get; set; }
        public Nullable<int> IdColeccion { get; set; }
        public string IdLinea { get; set; }
    
        public virtual Colecciones Colecciones { get; set; }
        public virtual MaestroEdad MaestroEdad { get; set; }
        public virtual MaestroLinea MaestroLinea { get; set; }
    }
}
