//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpresaTransporte
    {
        public int id { get; set; }
        public string CODE { get; set; }
        public string TXT { get; set; }
        public Nullable<int> MULTIPLO { get; set; }
        public string COMPANY { get; set; }
    }
}
