//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empresa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empresa()
        {
            this.AcuerdosxCliente = new HashSet<AcuerdosxCliente>();
            this.Bancos = new HashSet<Bancos>();
            this.Clientes = new HashSet<Clientes>();
            this.Colecciones = new HashSet<Colecciones>();
            this.CuentasBancarias = new HashSet<CuentasBancarias>();
            this.FacturasxCliente = new HashSet<FacturasxCliente>();
            this.MonedasxEmpresa = new HashSet<MonedasxEmpresa>();
            this.SubFacturasxCliente = new HashSet<SubFacturasxCliente>();
            this.TiposdePago = new HashSet<TiposdePago>();
            this.TiposdePagoDetalle = new HashSet<TiposdePagoDetalle>();
            this.GrupoImpuestoArticulo = new HashSet<GrupoImpuestoArticulo>();
            this.GrupoImpuestoCliente = new HashSet<GrupoImpuestoCliente>();
            this.PedidosxCliente = new HashSet<PedidosxCliente>();
            this.ProductosxColeccion = new HashSet<ProductosxColeccion>();
            this.Usuarios_Empresas = new HashSet<Usuarios_Empresas>();
            this.Usuarios = new HashSet<Usuarios>();
            this.Encuesta = new HashSet<Encuesta>();
        }
    
        public string EmpresaId { get; set; }
        public string NombreEmpresa { get; set; }
        public string Telefono { get; set; }
        public string CorreoElectronico { get; set; }
        public string Logo { get; set; }
        public string Direccion { get; set; }
        public string RegistroTributario { get; set; }
        public Nullable<bool> Revision { get; set; }
        public string DocumentoFiscal { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AcuerdosxCliente> AcuerdosxCliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bancos> Bancos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Clientes> Clientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Colecciones> Colecciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CuentasBancarias> CuentasBancarias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FacturasxCliente> FacturasxCliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MonedasxEmpresa> MonedasxEmpresa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubFacturasxCliente> SubFacturasxCliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TiposdePago> TiposdePago { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TiposdePagoDetalle> TiposdePagoDetalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GrupoImpuestoArticulo> GrupoImpuestoArticulo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GrupoImpuestoCliente> GrupoImpuestoCliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PedidosxCliente> PedidosxCliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductosxColeccion> ProductosxColeccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuarios_Empresas> Usuarios_Empresas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuarios> Usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Encuesta> Encuesta { get; set; }
    }
}
