//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacturasxCliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FacturasxCliente()
        {
            this.SubFacturasxCliente = new HashSet<SubFacturasxCliente>();
            this.RecibosxCliente = new HashSet<RecibosxCliente>();
            this.RecibosxClienteFlotante = new HashSet<RecibosxClienteFlotante>();
            this.DocumentosTransitoxFactura = new HashSet<DocumentosTransitoxFactura>();
            this.RecibosProforma = new HashSet<RecibosProforma>();
        }
    
        public int IdFactura { get; set; }
        public string Factura { get; set; }
        public string CodigoCliente { get; set; }
        public string EmpresaId { get; set; }
        public string IdMoneda { get; set; }
        public string Tipo { get; set; }
        public Nullable<System.DateTime> FechaFactura { get; set; }
        public Nullable<System.DateTime> FechaVencimiento { get; set; }
        public Nullable<System.DateTime> FechaMaxDescuento { get; set; }
        public Nullable<decimal> TotalFactura { get; set; }
        public Nullable<decimal> Saldo { get; set; }
        public Nullable<decimal> PendienteFactura { get; set; }
        public Nullable<decimal> Descuento { get; set; }
        public string FacturaStatus { get; set; }
        public Nullable<int> NumeroPagos { get; set; }
        public string Referencia { get; set; }
        public string IdLinea { get; set; }
        public Nullable<int> IdTipoPedido { get; set; }
        public string IdAcuerdoxCliente { get; set; }
        public string NumeroFEL { get; set; }
        public string NumeroPedido { get; set; }
        public bool Actualizado { get; set; }
        public bool ExcepcionDescuento { get; set; }
    
        public virtual AcuerdosxCliente AcuerdosxCliente { get; set; }
        public virtual Clientes Clientes { get; set; }
        public virtual Empresa Empresa { get; set; }
        public virtual MaestroLinea MaestroLinea { get; set; }
        public virtual MaestroMoneda MaestroMoneda { get; set; }
        public virtual TiposdePedido TiposdePedido { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubFacturasxCliente> SubFacturasxCliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecibosxCliente> RecibosxCliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecibosxClienteFlotante> RecibosxClienteFlotante { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentosTransitoxFactura> DocumentosTransitoxFactura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecibosProforma> RecibosProforma { get; set; }
    }
}
