//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacturasEnCuotasAcuerdos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FacturasEnCuotasAcuerdos()
        {
            this.PagosAFacturasDeCuotas = new HashSet<PagosAFacturasDeCuotas>();
        }
    
        public int IdFacturaXCuota { get; set; }
        public int idCuotaXAcuerdo { get; set; }
        public string Factura { get; set; }
        public decimal Valor { get; set; }
        public Nullable<System.DateTime> FechaFactura { get; set; }
        public Nullable<System.DateTime> FechaVencimiento { get; set; }
    
        public virtual CuotasXAcuerdo CuotasXAcuerdo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PagosAFacturasDeCuotas> PagosAFacturasDeCuotas { get; set; }
    }
}
