//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacturasxCliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FacturasxCliente()
        {
            this.SubFacturasxCliente = new HashSet<SubFacturasxCliente>();
            this.RecibosxCliente = new HashSet<RecibosxCliente>();
        }
    
        public int IdFactura { get; set; }
        public string Factura { get; set; }
        public string CodigoCliente { get; set; }
        public string EmpresaId { get; set; }
        public string IdMoneda { get; set; }
        public string Tipo { get; set; }
        public Nullable<System.DateTime> FechaFactura { get; set; }
        public Nullable<System.DateTime> FechaVencimiento { get; set; }
        public Nullable<System.DateTime> FechaMaxDescuento { get; set; }
        public Nullable<decimal> TotalFactura { get; set; }
        public Nullable<decimal> Saldo { get; set; }
        public Nullable<decimal> PendienteFactura { get; set; }
        public Nullable<decimal> Descuento { get; set; }
        public string FacturaStatus { get; set; }
        public Nullable<int> NumeroPagos { get; set; }
        public string Referencia { get; set; }
        public string IdLinea { get; set; }
        public Nullable<int> IdTipoPedido { get; set; }
        public string IdAcuerdoxCliente { get; set; }
        public string NumeroFEL { get; set; }
    
        public virtual AcuerdosxCliente AcuerdosxCliente { get; set; }
        public virtual Clientes Clientes { get; set; }
        public virtual Empresa Empresa { get; set; }
        public virtual MaestroLinea MaestroLinea { get; set; }
        public virtual MaestroMoneda MaestroMoneda { get; set; }
        public virtual TiposdePedido TiposdePedido { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubFacturasxCliente> SubFacturasxCliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecibosxCliente> RecibosxCliente { get; set; }
    }
}
