//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class FirmasxPedido
    {
        public int IdFirmaxPedido { get; set; }
        public byte[] Firma { get; set; }
        public string PedidoId { get; set; }
        public Nullable<int> PedidoFlotanteId { get; set; }
    
        public virtual PedidosxCliente PedidosxCliente { get; set; }
        public virtual PedidosxClienteFlotante PedidosxClienteFlotante { get; set; }
    }
}
