//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class FisicoDisponible
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FisicoDisponible()
        {
            this.PrecioEspecifico = new HashSet<PrecioEspecifico>();
        }
    
        public int IdFisicoDisponible { get; set; }
        public string CodigoColor { get; set; }
        public string CodigoTalla { get; set; }
        public int IdProducto { get; set; }
        public Nullable<decimal> Disponible { get; set; }
        public Nullable<decimal> MinStock { get; set; }
        public string Sitio { get; set; }
        public string Almacen { get; set; }
        public int VentaMaxima { get; set; }
    
        public virtual Colores Colores { get; set; }
        public virtual ProductosxColeccion ProductosxColeccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrecioEspecifico> PrecioEspecifico { get; set; }
    }
}
