//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormularioIntroEncabezado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FormularioIntroEncabezado()
        {
            this.FormularioIntroDetalle = new HashSet<FormularioIntroDetalle>();
            this.FormularioIntroDetallexRoles = new HashSet<FormularioIntroDetallexRoles>();
        }
    
        public int codFormularioIntroEncabezado { get; set; }
        public string nombreFormularioIntro { get; set; }
        public string descripcionFormularioIntro { get; set; }
        public Nullable<bool> activo { get; set; }
        public System.DateTime fechaCreacion { get; set; }
        public string usuarioCreacion { get; set; }
        public Nullable<System.DateTime> fechaModificacion { get; set; }
        public string usuarioModificacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormularioIntroDetalle> FormularioIntroDetalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormularioIntroDetallexRoles> FormularioIntroDetallexRoles { get; set; }
    }
}
