//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormularioIntroDetallexRoles
    {
        public int codFormularioIntroDetallexRol { get; set; }
        public int IdRol { get; set; }
        public int codFormularioIntroEncabezado { get; set; }
        public int codFormularioIntroDetalle { get; set; }
        public bool activo { get; set; }
        public Nullable<System.DateTime> fechaCreacion { get; set; }
        public string usuarioCreacion { get; set; }
        public Nullable<System.DateTime> fechaModificacion { get; set; }
        public string usuarioModificacion { get; set; }
    
        public virtual FormularioIntroDetalle FormularioIntroDetalle { get; set; }
        public virtual FormularioIntroEncabezado FormularioIntroEncabezado { get; set; }
    }
}
