//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Funciones_Roles
    {
        public int Id { get; set; }
        public int IdRol { get; set; }
        public int IdFuncion { get; set; }
    
        public virtual Funciones Funciones { get; set; }
        public virtual Roles Roles { get; set; }
        public virtual Funciones_Roles Funciones_Roles1 { get; set; }
        public virtual Funciones_Roles Funciones_Roles2 { get; set; }
    }
}
