//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Funciones_Roles
    {
        public int Id { get; set; }
        public int IdRol { get; set; }
        public int IdFuncion { get; set; }
        public Nullable<bool> Status { get; set; }
        public string createdby { get; set; }
        public Nullable<System.DateTime> createddate { get; set; }
        public string modifiedby { get; set; }
        public Nullable<System.DateTime> modifieddate { get; set; }
    
        public virtual Funciones Funciones { get; set; }
        public virtual Roles Roles { get; set; }
        public virtual Funciones_Roles Funciones_Roles1 { get; set; }
        public virtual Funciones_Roles Funciones_Roles2 { get; set; }
    }
}
