//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class GastosViajeDetalle
    {
        public int IdGastoViajeDetalle { get; set; }
        public int IdCategoriaTipoGastoViaje { get; set; }
        public string UsuarioAsesor { get; set; }
        public string Proveedor { get; set; }
        public string NoFactura { get; set; }
        public string Descripcion { get; set; }
        public double ValorFactura { get; set; }
        public System.DateTime FechaFactura { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public byte[] Imagen { get; set; }
        public Nullable<int> IdEstado { get; set; }
        public string DescripcionAdmin { get; set; }
        public string MensajeAX { get; set; }
        public string DescripcionGasto { get; set; }
        public string Administrador { get; set; }
        public string serie { get; set; }
    
        public virtual CategoriaTipoGastoViaje CategoriaTipoGastoViaje { get; set; }
        public virtual Estado Estado { get; set; }
    }
}
