//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class GastoViajeGrupoImpuesto
    {
        public string empresaID { get; set; }
        public string grupoImpuestoGravado { get; set; }
        public string grupoImpuestoArticuloGravado { get; set; }
        public string grupoImpuestoExento { get; set; }
        public string grupoImpuestoArticuloExento { get; set; }
    }
}
