//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class GastosViajeDetalle
    {
        public int IdGastoViajeDetalle { get; set; }
        public int IdCategoriaTipoGastoViaje { get; set; }
        public string UsuarioAsesor { get; set; }
        public string Proveedor { get; set; }
        public string NoFactura { get; set; }
        public string Descripcion { get; set; }
        public double ValorFactura { get; set; }
        public System.DateTime FechaFactura { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public byte[] Imagen { get; set; }
        public Nullable<int> IdEstado { get; set; }
        public string DescripcionAdmin { get; set; }
        public string MensajeAX { get; set; }
        public string DescripcionGasto { get; set; }
        public string Administrador { get; set; }
        public string serie { get; set; }
        public Nullable<double> importeExento { get; set; }
        public Nullable<double> importeGravado { get; set; }
    
        public virtual Estado Estado { get; set; }
        public virtual CategoriaTipoGastoViaje CategoriaTipoGastoViaje { get; set; }
    }
}
