//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class GastoViajeGrupoImpuesto
    {
        public string empresaID { get; set; }
        public string grupoImpuestoGravado { get; set; }
        public string grupoImpuestoArticuloGravado { get; set; }
        public string grupoImpuestoExento { get; set; }
        public string grupoImpuestoArticuloExento { get; set; }
    }
}
