//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class GESTORES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GESTORES()
        {
            this.GESTORES1 = new HashSet<GESTORES>();
            this.LISTA_EJECUCION = new HashSet<LISTA_EJECUCION>();
            this.LISTA_EJECUCION1 = new HashSet<LISTA_EJECUCION>();
            this.LISTA_EJECUCION_MANUAL = new HashSet<LISTA_EJECUCION_MANUAL>();
            this.LISTA_EJECUCION_ESPECIFICO = new HashSet<LISTA_EJECUCION_ESPECIFICO>();
        }
    
        public int ID { get; set; }
        public string NOMBRE { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<int> ID_GP { get; set; }
        public Nullable<bool> STATUS { get; set; }
        public System.Guid ROWID { get; set; }
        public Nullable<System.DateTime> ULT_SINCRONIZACION { get; set; }
        public int T_MIN_SINC { get; set; }
        public bool FORZAR { get; set; }
        public int NIVEL_PRIORIDAD { get; set; }
        public Nullable<int> GRUPO { get; set; }
        public Nullable<int> ORDEN { get; set; }
        public Nullable<int> ID_MODULO { get; set; }
        public string ETIQUETA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GESTORES> GESTORES1 { get; set; }
        public virtual GESTORES GESTORES2 { get; set; }
        public virtual MODULOS MODULOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LISTA_EJECUCION> LISTA_EJECUCION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LISTA_EJECUCION> LISTA_EJECUCION1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LISTA_EJECUCION_MANUAL> LISTA_EJECUCION_MANUAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LISTA_EJECUCION_ESPECIFICO> LISTA_EJECUCION_ESPECIFICO { get; set; }
    }
}
