//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class GrupoImpuestoCliente
    {
        public int IdGrupoImpuesto { get; set; }
        public string GrupoCliente { get; set; }
        public string GrupoImpuesto { get; set; }
        public decimal Porcentaje { get; set; }
        public string Empresa { get; set; }
        public bool Activo { get; set; }
    
        public virtual Empresa Empresa1 { get; set; }
    }
}
