//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class GrupoImpuestoCliente
    {
        public int IdGrupoImpuesto { get; set; }
        public string GrupoCliente { get; set; }
        public string GrupoImpuesto { get; set; }
        public decimal Porcentaje { get; set; }
        public string Empresa { get; set; }
        public bool Activo { get; set; }
    
        public virtual Empresa Empresa1 { get; set; }
    }
}
