//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class IncidenciaVisitaDetalle
    {
        public int Id { get; set; }
        public int IdIncidenciaVisita { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Fotografia { get; set; }
    
        public virtual IncidenciaVisita IncidenciaVisita { get; set; }
    }
}
