//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class IncidenciaVisita
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IncidenciaVisita()
        {
            this.IncidenciaVisitaDetalle = new HashSet<IncidenciaVisitaDetalle>();
        }
    
        public int Id { get; set; }
        public int IdAsignacionxAsesor { get; set; }
        public string Observacion { get; set; }
        public int IdEstadosIncidencia { get; set; }
        public int IdTipoIncidencia { get; set; }
        public string UsuarioResponsable { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
    
        public virtual AsignacionxAsesor AsignacionxAsesor { get; set; }
        public virtual EstadosIncidencia EstadosIncidencia { get; set; }
        public virtual TipoIncidencia TipoIncidencia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IncidenciaVisitaDetalle> IncidenciaVisitaDetalle { get; set; }
    }
}
