//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventarioDetalle
    {
        public int id { get; set; }
        public Nullable<int> inventarioId { get; set; }
        public Nullable<int> productoId { get; set; }
        public string codigoColor { get; set; }
        public string codigoTalla { get; set; }
        public Nullable<int> cantidad { get; set; }
    
        public virtual InventariosCliente InventariosCliente { get; set; }
        public virtual ProductosxColeccion ProductosxColeccion { get; set; }
    }
}
