//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventariosCliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InventariosCliente()
        {
            this.InventarioDetalle = new HashSet<InventarioDetalle>();
        }
    
        public int id { get; set; }
        public string numInventario { get; set; }
        public string codigoCliente { get; set; }
        public string empresaId { get; set; }
        public string codigoAsesor { get; set; }
        public System.DateTime fechaCrea { get; set; }
        public System.DateTime fechaModificado { get; set; }
        public bool completo { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Empresa Empresa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventarioDetalle> InventarioDetalle { get; set; }
    }
}
