//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class LISTA_EJECUCION_ESPECIFICO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LISTA_EJECUCION_ESPECIFICO()
        {
            this.PARAMETROS_LE_ESPECIFICO = new HashSet<PARAMETROS_LE_ESPECIFICO>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ID_GESTOR { get; set; }
        public bool EN_ESPERA { get; set; }
        public bool EN_EJECUCION { get; set; }
        public bool FINALIZADO { get; set; }
        public string USUARIO { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PARAMETROS_LE_ESPECIFICO> PARAMETROS_LE_ESPECIFICO { get; set; }
    }
}
