//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListasPreciosPaquetes
    {
        public int Id { get; set; }
        public Nullable<int> IdColeccion { get; set; }
        public string GrupoPrecio { get; set; }
        public string EmpresaId { get; set; }
        public Nullable<System.DateTime> FechaUltSincronizacion { get; set; }
    
        public virtual Colecciones Colecciones { get; set; }
        public virtual Empresa Empresa { get; set; }
        public virtual MaestroGrupoPrecio MaestroGrupoPrecio { get; set; }
    }
}
