//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class LISTA_EJECUCION_MANUAL
    {
        public int ID { get; set; }
        public Nullable<int> ID_GESTOR { get; set; }
        public bool EN_ESPERA { get; set; }
        public bool EN_EJECUCION { get; set; }
        public bool FINALIZADO { get; set; }
        public string USUARIO { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
    
        public virtual GESTORES GESTORES { get; set; }
    }
}
