//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class LISTA_EJECUCION_MANUAL
    {
        public int ID { get; set; }
        public Nullable<int> ID_GESTOR { get; set; }
        public bool EN_ESPERA { get; set; }
        public bool EN_EJECUCION { get; set; }
        public bool FINALIZADO { get; set; }
        public string USUARIO { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
    }
}
