//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOG_EJECUCION
    {
        public int ID { get; set; }
        public Nullable<int> ID_LISTA_EJECUCION { get; set; }
        public int STATUS { get; set; }
        public string MENSAJE { get; set; }
        public System.DateTime FECHA_INICIO { get; set; }
        public System.DateTime FECHA_FINAL { get; set; }
        public int REG_OBTENIDOS { get; set; }
        public int REG_NUE { get; set; }
        public int REG_ACT { get; set; }
        public int REG_ELI { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public int REG_PROCESADOS { get; set; }
        public int REG_CORRECTOS { get; set; }
        public int REG_INCORRECTOS { get; set; }
    
        public virtual LISTA_EJECUCION LISTA_EJECUCION { get; set; }
    }
}
