//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogSesion
    {
        public int Id { get; set; }
        public int Usuario { get; set; }
        public string version_navegador { get; set; }
        public string IP_Publica { get; set; }
        public string Latitud { get; set; }
        public string Longitud { get; set; }
        public string Version_App { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
    }
}
