//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaestroLinea
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MaestroLinea()
        {
            this.AcuerdosxCliente = new HashSet<AcuerdosxCliente>();
            this.FacturasxCliente = new HashSet<FacturasxCliente>();
            this.ProductosxColeccion = new HashSet<ProductosxColeccion>();
            this.PedidosxCliente = new HashSet<PedidosxCliente>();
        }
    
        public string IdLinea { get; set; }
        public string Linea { get; set; }
        public string Url_Imagen { get; set; }
        public Nullable<bool> Revision { get; set; }
        public Nullable<bool> Visible { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AcuerdosxCliente> AcuerdosxCliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FacturasxCliente> FacturasxCliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductosxColeccion> ProductosxColeccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PedidosxCliente> PedidosxCliente { get; set; }
    }
}
