//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaestroMoneda
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MaestroMoneda()
        {
            this.AcuerdosxCliente = new HashSet<AcuerdosxCliente>();
            this.Clientes = new HashSet<Clientes>();
            this.CuentasBancarias = new HashSet<CuentasBancarias>();
            this.FacturasxCliente = new HashSet<FacturasxCliente>();
            this.MonedasxEmpresa = new HashSet<MonedasxEmpresa>();
            this.SubFacturasxCliente = new HashSet<SubFacturasxCliente>();
            this.PreciosxProducto = new HashSet<PreciosxProducto>();
            this.PrecioEspecifico = new HashSet<PrecioEspecifico>();
            this.DocumentosTransitoxFactura = new HashSet<DocumentosTransitoxFactura>();
            this.PedidosxCliente = new HashSet<PedidosxCliente>();
            this.PedidosxClienteFlotante = new HashSet<PedidosxClienteFlotante>();
        }
    
        public string IdMoneda { get; set; }
        public string Moneda { get; set; }
        public string Abreviacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AcuerdosxCliente> AcuerdosxCliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Clientes> Clientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CuentasBancarias> CuentasBancarias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FacturasxCliente> FacturasxCliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MonedasxEmpresa> MonedasxEmpresa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubFacturasxCliente> SubFacturasxCliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PreciosxProducto> PreciosxProducto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrecioEspecifico> PrecioEspecifico { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentosTransitoxFactura> DocumentosTransitoxFactura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PedidosxCliente> PedidosxCliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PedidosxClienteFlotante> PedidosxClienteFlotante { get; set; }
    }
}
