//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaestroBodegaAlmacenes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MaestroBodegaAlmacenes()
        {
            this.PaqueteBodegaEspecifico = new HashSet<PaqueteBodegaEspecifico>();
            this.UbicacionesXAlmacen = new HashSet<UbicacionesXAlmacen>();
        }
    
        public int AlmacenId { get; set; }
        public string Almacen { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> SitioId { get; set; }
        public string EmpresaId { get; set; }
        public string Etiqueta { get; set; }
        public bool Estatus { get; set; }
        public string ModificadoPor { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public bool ActivoDevolucion { get; set; }
    
        public virtual Empresa Empresa { get; set; }
        public virtual MaestroBodegaSitios MaestroBodegaSitios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaqueteBodegaEspecifico> PaqueteBodegaEspecifico { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UbicacionesXAlmacen> UbicacionesXAlmacen { get; set; }
    }
}
