//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class MailSpConfig
    {
        public int Id { get; set; }
        public string ServicioID { get; set; }
        public string StoreProcedureName { get; set; }
        public string ParamName { get; set; }
        public string ParamValue { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string ParamType { get; set; }
    }
}
