//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class MailServicios
    {
        public string Modulo { get; set; }
        public string ServicioID { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string UsuarioCreacion { get; set; }
        public string Header { get; set; }
        public string ValidaType { get; set; }
        public string Consulta { get; set; }
        public string Footer { get; set; }
        public string Estado { get; set; }
        public string valida_empresaid { get; set; }
    
        public virtual MailModulos MailModulos { get; set; }
    }
}
