//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class MailReceptors
    {
        public string ServicioID { get; set; }
        public string EmpresaId { get; set; }
        public string CorreoElectronico { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string UsuarioCreacion { get; set; }
        public string Estado { get; set; }
        public Nullable<System.DateTime> FechaModifiacion { get; set; }
    }
}
