//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonedasxEmpresa
    {
        public int IdMonedaxEmpresa { get; set; }
        public string EmpresaId { get; set; }
        public string IdMoneda { get; set; }
    
        public virtual Empresa Empresa { get; set; }
        public virtual MaestroMoneda MaestroMoneda { get; set; }
    }
}
