//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonedasxEmpresa
    {
        public int IdMonedaxEmpresa { get; set; }
        public string EmpresaId { get; set; }
        public string IdMoneda { get; set; }
    
        public virtual Empresa Empresa { get; set; }
        public virtual MaestroMoneda MaestroMoneda { get; set; }
    }
}
