//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class MotivosDevConAprobacion
    {
        public int IdMotivoDevConAprobacion { get; set; }
        public int IdMotivoDevolucion { get; set; }
        public int IdUsuario { get; set; }
        public bool Estado { get; set; }
        public int UsuarioCrea { get; set; }
        public System.DateTime FechaCrea { get; set; }
        public Nullable<int> UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
        public Nullable<int> Nivel { get; set; }
    
        public virtual MotivosDevolucion MotivosDevolucion { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        public virtual Usuarios Usuarios1 { get; set; }
        public virtual Usuarios Usuarios2 { get; set; }
    }
}
