//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class MotivosDevolucionDetalle
    {
        public int idMotivoDevDetalle { get; set; }
        public string CodigoMotivoDevDetalle { get; set; }
        public int idMotivoDevolucion { get; set; }
        public string Descripcion { get; set; }
        public string EmpresaId { get; set; }
        public bool Estado { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
        public Nullable<int> UsuarioModifica { get; set; }
    
        public virtual Empresa Empresa { get; set; }
        public virtual MotivosDevolucion MotivosDevolucion { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
