//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class MotivosDevConAprobacion
    {
        public int IdMotivoDevConAprobacion { get; set; }
        public int IdMotivoDevolucion { get; set; }
        public int IdUsuario { get; set; }
        public bool Estado { get; set; }
        public int UsuarioCrea { get; set; }
        public System.DateTime FechaCrea { get; set; }
        public Nullable<int> UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
    
        public virtual MotivosDevolucion MotivosDevolucion { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        public virtual Usuarios Usuarios1 { get; set; }
        public virtual Usuarios Usuarios2 { get; set; }
    }
}
