//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class MotivosDevolucionDetalle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MotivosDevolucionDetalle()
        {
            this.Devolucion = new HashSet<Devolucion>();
        }
    
        public int idMotivoDevDetalle { get; set; }
        public string CodigoMotivoDevDetalle { get; set; }
        public int idMotivoDevolucion { get; set; }
        public string Descripcion { get; set; }
        public string EmpresaId { get; set; }
        public bool Estado { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
        public Nullable<int> UsuarioModifica { get; set; }
    
        public virtual Empresa Empresa { get; set; }
        public virtual MotivosDevolucion MotivosDevolucion { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Devolucion> Devolucion { get; set; }
    }
}
