//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class MotivosDevolucion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MotivosDevolucion()
        {
            this.MotivosDevolucionDetalle = new HashSet<MotivosDevolucionDetalle>();
            this.MotivosDevConAprobacion = new HashSet<MotivosDevConAprobacion>();
        }
    
        public int IdMotivoDevolucion { get; set; }
        public string CodigoMotivoDevolucion { get; set; }
        public string Descripcion { get; set; }
        public string EmpresaId { get; set; }
        public bool aprobacionObligatoria { get; set; }
        public bool Estado { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
        public Nullable<int> UsuarioModifica { get; set; }
    
        public virtual Empresa Empresa { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MotivosDevolucionDetalle> MotivosDevolucionDetalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MotivosDevConAprobacion> MotivosDevConAprobacion { get; set; }
    }
}
