//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class PagosAFacturasDeCuotas
    {
        public int IdPagosAFacturasDeCuota { get; set; }
        public int IdFacturaXCuota { get; set; }
        public string NumeroDocumento { get; set; }
        public Nullable<decimal> Valor { get; set; }
        public Nullable<System.DateTime> FechaLiquidacion { get; set; }
        public Nullable<System.DateTime> FechaDeposito { get; set; }
    
        public virtual FacturasEnCuotasAcuerdos FacturasEnCuotasAcuerdos { get; set; }
    }
}
