//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class PagosAFacturasDeCuotas
    {
        public int IdPagosAFacturasDeCuota { get; set; }
        public int IdFacturaXCuota { get; set; }
        public string NumeroDocumento { get; set; }
        public Nullable<decimal> Valor { get; set; }
        public Nullable<System.DateTime> FechaLiquidacion { get; set; }
        public Nullable<System.DateTime> FechaDeposito { get; set; }
    
        public virtual FacturasEnCuotasAcuerdos FacturasEnCuotasAcuerdos { get; set; }
    }
}
