//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class PantallasxUsuario
    {
        public int IdPantallaUsuario { get; set; }
        public string IdUsuario { get; set; }
        public Nullable<int> IdPantalla { get; set; }
        public Nullable<bool> Activa { get; set; }
    
        public virtual Pantallas Pantallas { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
