//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pantallas_Funciones
    {
        public int Id { get; set; }
        public int IdPantalla { get; set; }
        public int IdFuncion { get; set; }
        public bool Status { get; set; }
    
        public virtual Funciones Funciones { get; set; }
        public virtual Pantallas Pantallas { get; set; }
    }
}
