//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class PantallasxUsuario
    {
        public int IdPantallaUsuario { get; set; }
        public string IdUsuario { get; set; }
        public Nullable<int> IdPantalla { get; set; }
        public Nullable<bool> Activa { get; set; }
    
        public virtual Pantallas Pantallas { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
