//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pantallas_Funciones
    {
        public int Id { get; set; }
        public int IdPantalla { get; set; }
        public int IdFuncion { get; set; }
    
        public virtual Funciones Funciones { get; set; }
        public virtual Pantallas Pantallas { get; set; }
    }
}
