//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaqueteBodegaEspecifico
    {
        public int Id { get; set; }
        public string EmpresaId { get; set; }
        public Nullable<int> ColeccionId { get; set; }
        public string Etiqueta { get; set; }
        public Nullable<bool> Estado { get; set; }
        public string Sitio { get; set; }
        public string Almacen { get; set; }
        public string CreadoPor { get; set; }
        public string ModificadoPor { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
    
        public virtual Colecciones Colecciones { get; set; }
        public virtual Empresa Empresa { get; set; }
    }
}
