//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARAMETROS_LE_ESPECIFICO
    {
        public int ID { get; set; }
        public Nullable<int> ID_LISTA_EJECUCION { get; set; }
        public string TIPO { get; set; }
        public string VALOR { get; set; }
        public string USUARIO { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
    
        public virtual LISTA_EJECUCION_ESPECIFICO LISTA_EJECUCION_ESPECIFICO { get; set; }
    }
}
