//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARAMETROS_LE_ESPECIFICO
    {
        public int ID { get; set; }
        public Nullable<int> ID_LISTA_EJECUCION { get; set; }
        public string TIPO { get; set; }
        public string VALOR { get; set; }
        public string USUARIO { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
    
        public virtual LISTA_EJECUCION_ESPECIFICO LISTA_EJECUCION_ESPECIFICO { get; set; }
    }
}
