//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class PedidosxClienteFlotante
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PedidosxClienteFlotante()
        {
            this.PedidosDetalleFlotante = new HashSet<PedidosDetalleFlotante>();
        }
    
        public int Id { get; set; }
        public string PedidoId { get; set; }
        public string NumeroPedido { get; set; }
        public Nullable<int> IdTipoPedido { get; set; }
        public Nullable<int> IdColeccion { get; set; }
        public string CodigoCliente { get; set; }
        public string AcuerdoVenta { get; set; }
        public string EmpresaId { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<System.DateTime> FechaEntrega { get; set; }
        public string CodigoAsesor { get; set; }
        public string Observacion { get; set; }
        public Nullable<decimal> TotalUnidades { get; set; }
        public Nullable<decimal> Subtotal { get; set; }
        public Nullable<decimal> TotalImpuesto { get; set; }
        public Nullable<decimal> TotalDescuento { get; set; }
        public Nullable<decimal> TotalPedido { get; set; }
        public Nullable<bool> Mocked { get; set; }
        public Nullable<decimal> Accuracy { get; set; }
        public Nullable<decimal> Altitude { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public string Error { get; set; }
        public string IdLinea { get; set; }
        public string idMoneda { get; set; }
        public Nullable<int> IdEstado { get; set; }
        public bool Sincronizado { get; set; }
        public Nullable<int> ClienteContadoId { get; set; }
        public string ModoVenta { get; set; }
        public Nullable<decimal> Flete { get; set; }
        public bool RequiereEntrega { get; set; }
        public Nullable<bool> Procesando { get; set; }
        public string ErrorAx { get; set; }
        public int ESTADO { get; set; }
        public string PedidoIdGenerado { get; set; }
        public string EditedBy { get; set; }
        public Nullable<System.DateTime> EditedDate { get; set; }
        public Nullable<bool> BodegaEspecifica { get; set; }
        public string Sitio { get; set; }
        public string Almacen { get; set; }
        public string Ubicacion { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Colecciones Colecciones { get; set; }
        public virtual Empresa Empresa { get; set; }
        public virtual EstadosPedido EstadosPedido { get; set; }
        public virtual MaestroLinea MaestroLinea { get; set; }
        public virtual MaestroMoneda MaestroMoneda { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PedidosDetalleFlotante> PedidosDetalleFlotante { get; set; }
        public virtual TiposdePedido TiposdePedido { get; set; }
    }
}
