//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class PedidosDetalleFlotante
    {
        public int IdPedidoDetalle { get; set; }
        public Nullable<int> IdPedidoxClienteFlotante { get; set; }
        public string PedidoId { get; set; }
        public Nullable<int> IdProducto { get; set; }
        public string CodigoColor { get; set; }
        public string CodigoTalla { get; set; }
        public Nullable<int> Linea { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public Nullable<decimal> PrecioUnitario { get; set; }
        public Nullable<decimal> MontoLinea { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string CodigoAsesor { get; set; }
    
        public virtual ProductosxColeccion ProductosxColeccion { get; set; }
        public virtual PedidosxClienteFlotante PedidosxClienteFlotante { get; set; }
    }
}
