//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrecioEspecifico
    {
        public int IdPrecioEspecifico { get; set; }
        public string IdMoneda { get; set; }
        public Nullable<int> IdProducto { get; set; }
        public string GrupoPrecio { get; set; }
        public Nullable<int> IdFisicoDisponible { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<System.DateTime> Desde { get; set; }
        public Nullable<System.DateTime> Hasta { get; set; }
    
        public virtual FisicoDisponible FisicoDisponible { get; set; }
        public virtual MaestroGrupoPrecio MaestroGrupoPrecio { get; set; }
        public virtual MaestroMoneda MaestroMoneda { get; set; }
        public virtual ProductosxColeccion ProductosxColeccion { get; set; }
    }
}
