//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class PreciosxProducto
    {
        public int IdPrecioxProducto { get; set; }
        public string GrupoPrecio { get; set; }
        public int IdProducto { get; set; }
        public string IdMoneda { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<System.DateTime> Desde { get; set; }
        public Nullable<System.DateTime> Hasta { get; set; }
    
        public virtual MaestroMoneda MaestroMoneda { get; set; }
        public virtual ProductosxColeccion ProductosxColeccion { get; set; }
    }
}
