//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Preguntas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Preguntas()
        {
            this.PreguntasOpciones = new HashSet<PreguntasOpciones>();
            this.RespuestaDetalle = new HashSet<RespuestaDetalle>();
        }
    
        public int Id { get; set; }
        public int SeccionEncuestaId { get; set; }
        public int TipoIngresoId { get; set; }
        public Nullable<int> GrupoOpcionesId { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public bool Obligatorio { get; set; }
        public bool RespuestaObligatorio { get; set; }
        public bool Status { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual Encuesta Encuesta { get; set; }
        public virtual GrupoOpciones GrupoOpciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PreguntasOpciones> PreguntasOpciones { get; set; }
        public virtual TiposIngreso TiposIngreso { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RespuestaDetalle> RespuestaDetalle { get; set; }
        public virtual Secciones Secciones { get; set; }
    }
}
