//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrioridadAsignacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PrioridadAsignacion()
        {
            this.AsignacionxAsesor = new HashSet<AsignacionxAsesor>();
        }
    
        public int idPrioridad { get; set; }
        public string NombrePrioridad { get; set; }
        public Nullable<bool> Estatus { get; set; }
        public string ColorBorde { get; set; }
        public string ColorRelleno { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AsignacionxAsesor> AsignacionxAsesor { get; set; }
    }
}
