//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductosxColeccion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductosxColeccion()
        {
            this.AtributosxProducto = new HashSet<AtributosxProducto>();
            this.ColoresxProducto = new HashSet<ColoresxProducto>();
            this.TallasxProducto = new HashSet<TallasxProducto>();
            this.PreciosxProducto = new HashSet<PreciosxProducto>();
            this.FisicoDisponible = new HashSet<FisicoDisponible>();
            this.PrecioEspecifico = new HashSet<PrecioEspecifico>();
            this.PedidosDetalle = new HashSet<PedidosDetalle>();
            this.FotografiasXProducto = new HashSet<FotografiasXProducto>();
            this.PedidosDetalleFlotante = new HashSet<PedidosDetalleFlotante>();
            this.DevolucionDetalle = new HashSet<DevolucionDetalle>();
            this.InventarioDetalle = new HashSet<InventarioDetalle>();
        }
    
        public int IdProducto { get; set; }
        public string CodigoProducto { get; set; }
        public Nullable<int> IdColeccion { get; set; }
        public string NombreProducto { get; set; }
        public string IdLinea { get; set; }
        public string CodigoGrupoTalla { get; set; }
        public Nullable<bool> BackOrder { get; set; }
        public Nullable<decimal> Multiplo { get; set; }
        public string IdEdad { get; set; }
        public string GrupoImpuesto { get; set; }
        public string EmpresaId { get; set; }
        public bool VisibleParaVentas { get; set; }
        public Nullable<decimal> CantidadMinima { get; set; }
        public bool StockVisible { get; set; }
        public bool Deshabilitado { get; set; }
        public bool InOut { get; set; }
        public int Prioridad { get; set; }
        public bool TieneVentaMaxima { get; set; }
        public bool Nuevo { get; set; }
        public bool PiezaSuelta { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AtributosxProducto> AtributosxProducto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ColoresxProducto> ColoresxProducto { get; set; }
        public virtual GrupoTalla GrupoTalla { get; set; }
        public virtual MaestroEdad MaestroEdad { get; set; }
        public virtual MaestroLinea MaestroLinea { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TallasxProducto> TallasxProducto { get; set; }
        public virtual Empresa Empresa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PreciosxProducto> PreciosxProducto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FisicoDisponible> FisicoDisponible { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrecioEspecifico> PrecioEspecifico { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PedidosDetalle> PedidosDetalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FotografiasXProducto> FotografiasXProducto { get; set; }
        public virtual Colecciones Colecciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PedidosDetalleFlotante> PedidosDetalleFlotante { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DevolucionDetalle> DevolucionDetalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventarioDetalle> InventarioDetalle { get; set; }
    }
}
