//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class PromesaPago
    {
        public int IdPromesaPago { get; set; }
        public int IdAsignacionXAsesor { get; set; }
        public System.DateTime FechaPromesa { get; set; }
        public decimal Valor { get; set; }
        public System.DateTime FechaCrea { get; set; }
        public int UsuarioCrea { get; set; }
    
        public virtual AsignacionxAsesor AsignacionxAsesor { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
