//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class PromesaPago
    {
        public int IdPromesaPago { get; set; }
        public int IdAsignacionXAsesor { get; set; }
        public System.DateTime FechaPromesa { get; set; }
        public decimal Valor { get; set; }
        public System.DateTime FechaCrea { get; set; }
        public int UsuarioCrea { get; set; }
    
        public virtual AsignacionxAsesor AsignacionxAsesor { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
