//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class RazonNoVentaCausa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RazonNoVentaCausa()
        {
            this.BitacoraVisitasCliente = new HashSet<BitacoraVisitasCliente>();
        }
    
        public int IdRazonNoVentaCausa { get; set; }
        public Nullable<int> IdRazonNoVentaTipo { get; set; }
        public string Causa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BitacoraVisitasCliente> BitacoraVisitasCliente { get; set; }
        public virtual RazonNoVentaTipo RazonNoVentaTipo { get; set; }
    }
}
