//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecibosDetalle
    {
        public int IdReciboDetalle { get; set; }
        public Nullable<int> ReciboId { get; set; }
        public Nullable<int> IdSubFactura { get; set; }
        public Nullable<decimal> Valor { get; set; }
        public Nullable<decimal> Descuento { get; set; }
    
        public virtual SubFacturasxCliente SubFacturasxCliente { get; set; }
        public virtual RecibosxCliente RecibosxCliente { get; set; }
    }
}
