//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecibosxClienteFlotante
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RecibosxClienteFlotante()
        {
            this.RecibosDetalleFlotante = new HashSet<RecibosDetalleFlotante>();
        }
    
        public int ReciboId { get; set; }
        public string NumeroRecibo { get; set; }
        public string CodigoCliente { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> IdTipoPago { get; set; }
        public string SpecPago { get; set; }
        public string Referencia { get; set; }
        public Nullable<System.DateTime> FechaCheque { get; set; }
        public Nullable<int> IdBanco { get; set; }
        public Nullable<int> IdCuentaBancaria { get; set; }
        public Nullable<decimal> Valor { get; set; }
        public string IdMoneda { get; set; }
        public Nullable<bool> Sincronizado { get; set; }
        public string CodigoAsesor { get; set; }
        public Nullable<int> IdFactura { get; set; }
        public Nullable<decimal> Descuento { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public int Estado { get; set; }
        public string ReciboIdGenerado { get; set; }
        public Nullable<bool> EsContado { get; set; }
        public string NumPedido { get; set; }
        public string Tipo { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
    
        public virtual FacturasxCliente FacturasxCliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecibosDetalleFlotante> RecibosDetalleFlotante { get; set; }
    }
}
