//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecibosProformaDetalle
    {
        public int IdProformaDetalle { get; set; }
        public Nullable<int> ProformaId { get; set; }
        public Nullable<int> IdSubFactura { get; set; }
        public Nullable<decimal> Valor { get; set; }
        public Nullable<decimal> Descuento { get; set; }
        public bool EsAbono { get; set; }
        public Nullable<decimal> ValorFactura { get; set; }
    
        public virtual RecibosProforma RecibosProforma { get; set; }
        public virtual SubFacturasxCliente SubFacturasxCliente { get; set; }
    }
}
