//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistroDeTraslado
    {
        public int IdRegistroDeTraslado { get; set; }
        public string PedidoBase { get; set; }
        public string PedidoTraslado { get; set; }
        public string CreadoPor { get; set; }
        public System.DateTime FechaDeCreacion { get; set; }
        public string Company { get; set; }
    }
}
