//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class RespuestaDetalle
    {
        public int Id { get; set; }
        public int RespuestaId { get; set; }
        public int PreguntaId { get; set; }
        public Nullable<int> PreguntaOpcionesId { get; set; }
        public string RespuestaAlfanumerica { get; set; }
        public Nullable<int> RespuestaNumerica { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual Preguntas Preguntas { get; set; }
        public virtual PreguntasOpciones PreguntasOpciones { get; set; }
        public virtual Respuestas Respuestas { get; set; }
    }
}
