//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class RespuestaAnidadaDetalle
    {
        public int Id { get; set; }
        public int RespuestaId { get; set; }
        public int PreguntaAnidadaId { get; set; }
        public Nullable<int> PreguntaOpcionesAnidadasId { get; set; }
        public string RespuestaAlfanumerica { get; set; }
        public Nullable<int> RespuestaNumerica { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual PreguntasAnidadas PreguntasAnidadas { get; set; }
        public virtual PreguntasOpcionesAnidadas PreguntasOpcionesAnidadas { get; set; }
        public virtual Respuestas Respuestas { get; set; }
    }
}
