//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class RutasxAsesor
    {
        public int IdRutasxAsesor { get; set; }
        public string CodigoRuta { get; set; }
        public string CodigoAsesor { get; set; }
    
        public virtual Rutas Rutas { get; set; }
    }
}
