//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servicio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Servicio()
        {
            this.ContactoServicio = new HashSet<ContactoServicio>();
        }
    
        public int Id { get; set; }
        public string Codigo { get; set; }
        public string TipoServicio { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime ProximaEjecucionEnvio { get; set; }
        public Nullable<System.DateTime> UltimaEjecucionEnvio { get; set; }
        public System.DateTime ProximaEjecucionGenerarArchivo { get; set; }
        public Nullable<System.DateTime> UltimaEjecucionGenerarArchivo { get; set; }
        public bool Automatico { get; set; }
        public bool Activo { get; set; }
        public bool ReIniciar { get; set; }
        public bool ReIniciarGenerarcionArchivo { get; set; }
        public Nullable<int> NumeroEjecucion { get; set; }
        public string UsuarioModificion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public bool EstadoEjecucionSW { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContactoServicio> ContactoServicio { get; set; }
    }
}
