//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubFacturasxCliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SubFacturasxCliente()
        {
            this.RecibosDetalle = new HashSet<RecibosDetalle>();
        }
    
        public int IdSubFactura { get; set; }
        public string Factura { get; set; }
        public string CodigoCliente { get; set; }
        public string EmpresaId { get; set; }
        public string IdMoneda { get; set; }
        public string IdAcuerdoxCliente { get; set; }
        public Nullable<System.DateTime> FechaVencimiento { get; set; }
        public Nullable<System.DateTime> FechaMaxDescuento { get; set; }
        public Nullable<System.DateTime> FechaVencimientoDescuento { get; set; }
        public Nullable<decimal> Saldo { get; set; }
        public Nullable<decimal> SaldoDivisa { get; set; }
        public Nullable<decimal> Descuento { get; set; }
        public Nullable<decimal> PendientePago { get; set; }
        public string Referencia { get; set; }
        public string ReferenciaFacturas { get; set; }
        public string ReferenciaAcuerdo { get; set; }
        public Nullable<int> NumeroCuota { get; set; }
        public Nullable<decimal> ValorCuota { get; set; }
        public Nullable<decimal> ValorVencidoCuota { get; set; }
        public string ReferenciaCuotas { get; set; }
        public Nullable<int> IdFactura { get; set; }
        public string NumeroFEL { get; set; }
    
        public virtual AcuerdosxCliente AcuerdosxCliente { get; set; }
        public virtual Clientes Clientes { get; set; }
        public virtual Empresa Empresa { get; set; }
        public virtual FacturasxCliente FacturasxCliente { get; set; }
        public virtual MaestroMoneda MaestroMoneda { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecibosDetalle> RecibosDetalle { get; set; }
    }
}
