//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubFacturasxCliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SubFacturasxCliente()
        {
            this.RecibosDetalle = new HashSet<RecibosDetalle>();
            this.RecibosDetalleFlotante = new HashSet<RecibosDetalleFlotante>();
            this.DocumentosTransitoxFactura = new HashSet<DocumentosTransitoxFactura>();
            this.RecibosProformaDetalle = new HashSet<RecibosProformaDetalle>();
            this.DocumentosAplicadosAFacturas = new HashSet<DocumentosAplicadosAFacturas>();
        }
    
        public int IdSubFactura { get; set; }
        public string Factura { get; set; }
        public string CodigoCliente { get; set; }
        public string EmpresaId { get; set; }
        public string IdMoneda { get; set; }
        public string IdAcuerdoxCliente { get; set; }
        public Nullable<System.DateTime> FechaVencimiento { get; set; }
        public Nullable<System.DateTime> FechaMaxDescuento { get; set; }
        public Nullable<System.DateTime> FechaVencimientoDescuento { get; set; }
        public Nullable<decimal> Saldo { get; set; }
        public Nullable<decimal> SaldoDivisa { get; set; }
        public Nullable<decimal> Descuento { get; set; }
        public Nullable<decimal> PendientePago { get; set; }
        public string Referencia { get; set; }
        public string ReferenciaFacturas { get; set; }
        public string ReferenciaAcuerdo { get; set; }
        public Nullable<int> NumeroCuota { get; set; }
        public Nullable<decimal> ValorCuota { get; set; }
        public Nullable<decimal> ValorVencidoCuota { get; set; }
        public string ReferenciaCuotas { get; set; }
        public Nullable<int> IdFactura { get; set; }
        public string NumeroFEL { get; set; }
        public Nullable<bool> completaCuota { get; set; }
        public Nullable<decimal> Valor { get; set; }
        public Nullable<decimal> Flete { get; set; }
    
        public virtual AcuerdosxCliente AcuerdosxCliente { get; set; }
        public virtual Clientes Clientes { get; set; }
        public virtual Empresa Empresa { get; set; }
        public virtual FacturasxCliente FacturasxCliente { get; set; }
        public virtual MaestroMoneda MaestroMoneda { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecibosDetalle> RecibosDetalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecibosDetalleFlotante> RecibosDetalleFlotante { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentosTransitoxFactura> DocumentosTransitoxFactura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecibosProformaDetalle> RecibosProformaDetalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentosAplicadosAFacturas> DocumentosAplicadosAFacturas { get; set; }
    }
}
