//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class TallasxProducto
    {
        public int IdTallaxProducto { get; set; }
        public Nullable<int> IdProducto { get; set; }
        public Nullable<int> IdTallaxGrupo { get; set; }
    
        public virtual ProductosxColeccion ProductosxColeccion { get; set; }
        public virtual TallasXGrupo TallasXGrupo { get; set; }
    }
}
