//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class TallasXGrupo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TallasXGrupo()
        {
            this.DistribucionxTalla = new HashSet<DistribucionxTalla>();
            this.TallasxProducto = new HashSet<TallasxProducto>();
        }
    
        public int IdTallaxGrupo { get; set; }
        public string CodigoTalla { get; set; }
        public Nullable<decimal> Orden { get; set; }
        public string CodigoGrupoTalla { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DistribucionxTalla> DistribucionxTalla { get; set; }
        public virtual GrupoTalla GrupoTalla { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TallasxProducto> TallasxProducto { get; set; }
    }
}
