//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class TiempoFueraAgenda
    {
        public int id { get; set; }
        public string codigoAsesor { get; set; }
        public Nullable<System.DateTime> horaEntrada { get; set; }
        public Nullable<decimal> latitudEntrada { get; set; }
        public Nullable<decimal> longitudEntrada { get; set; }
        public Nullable<System.DateTime> horaSalida { get; set; }
        public Nullable<decimal> latitudSalida { get; set; }
        public Nullable<decimal> longitudSalida { get; set; }
        public Nullable<int> motivoTiempoFueraId { get; set; }
        public string descripcion { get; set; }
    
        public virtual MotivoTiempoFuera MotivoTiempoFuera { get; set; }
    }
}
