//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class TiposdePedido
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TiposdePedido()
        {
            this.AcuerdosxCliente = new HashSet<AcuerdosxCliente>();
            this.FacturasxCliente = new HashSet<FacturasxCliente>();
            this.PedidosxCliente = new HashSet<PedidosxCliente>();
            this.PedidosxClienteFlotante = new HashSet<PedidosxClienteFlotante>();
        }
    
        public int IdTipoPedido { get; set; }
        public string TipoPedido { get; set; }
        public Nullable<bool> HabilitaEstilos { get; set; }
        public string Url_Imagen { get; set; }
        public Nullable<bool> Aplica_Todos { get; set; }
        public Nullable<bool> Restrictivo { get; set; }
        public bool AgruparPorCuotas { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AcuerdosxCliente> AcuerdosxCliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FacturasxCliente> FacturasxCliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PedidosxCliente> PedidosxCliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PedidosxClienteFlotante> PedidosxClienteFlotante { get; set; }
    }
}
