//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class TiposdePagoDetalle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TiposdePagoDetalle()
        {
            this.AnticiposxCliente = new HashSet<AnticiposxCliente>();
            this.RecibosxCliente = new HashSet<RecibosxCliente>();
        }
    
        public int IdTipoPagoDetalle { get; set; }
        public string Codigo { get; set; }
        public string CodigoDetalle { get; set; }
        public string Descripcion { get; set; }
        public string EmpresaId { get; set; }
        public Nullable<int> IdTipoPago { get; set; }
    
        public virtual Empresa Empresa { get; set; }
        public virtual TiposdePago TiposdePago { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnticiposxCliente> AnticiposxCliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecibosxCliente> RecibosxCliente { get; set; }
    }
}
