//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;

    public partial class TipoConfiguracionCorreoRol
    {
        public int Id { get; set; }
        public int TipoConfiguracionCorreoId { get; set; }
        public int RolId { get; set; }

        public virtual TipoConfiguracionCorreo TipoConfiguracionCorreo { get; set; }
        public virtual Roles Roles { get; set; }
    }
}
