//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransportePrecioCaja
    {
        public int id { get; set; }
        public string STATE { get; set; }
        public string COMPANY { get; set; }
        public Nullable<decimal> UNITVALUEBOXES { get; set; }
        public string CODE { get; set; }
    }
}
