//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class UbicacionesXAlmacen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UbicacionesXAlmacen()
        {
            this.Devolucion = new HashSet<Devolucion>();
        }
    
        public int UbicacionId { get; set; }
        public string CodigoUbicacion { get; set; }
        public Nullable<int> AlmacenId { get; set; }
        public bool Estatus { get; set; }
        public string ModificadoPor { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public bool ActivoDevolucion { get; set; }
    
        public virtual MaestroBodegaAlmacenes MaestroBodegaAlmacenes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Devolucion> Devolucion { get; set; }
    }
}
