//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuarios()
        {
            this.PantallasxUsuario = new HashSet<PantallasxUsuario>();
            this.Usuario_Rol = new HashSet<Usuario_Rol>();
            this.Usuarios_Empresas = new HashSet<Usuarios_Empresas>();
            this.Secciones_Usuarios = new HashSet<Secciones_Usuarios>();
            this.Respuestas = new HashSet<Respuestas>();
            this.LogSesion = new HashSet<LogSesion>();
            this.Usuarios_Asesores = new HashSet<Usuarios_Asesores>();
            this.MotivosDevolucion = new HashSet<MotivosDevolucion>();
            this.MotivosDevolucionDetalle = new HashSet<MotivosDevolucionDetalle>();
            this.MotivosDevConAprobacion = new HashSet<MotivosDevConAprobacion>();
            this.MotivosDevConAprobacion1 = new HashSet<MotivosDevConAprobacion>();
            this.MotivosDevConAprobacion2 = new HashSet<MotivosDevConAprobacion>();
            this.AprobacionDevoluciones = new HashSet<AprobacionDevoluciones>();
            this.AprobacionDevoluciones1 = new HashSet<AprobacionDevoluciones>();
            this.AprobacionDevoluciones2 = new HashSet<AprobacionDevoluciones>();
            this.Devolucion = new HashSet<Devolucion>();
            this.PromesaPago = new HashSet<PromesaPago>();
            this.BitacoraNoVentaEnVisitas = new HashSet<BitacoraNoVentaEnVisitas>();
            this.UsuarioLinea = new HashSet<UsuarioLinea>();
            this.InventariosCliente = new HashSet<InventariosCliente>();
        }
    
        public int Id { get; set; }
        public string usuario { get; set; }
        public string password { get; set; }
        public bool status { get; set; }
        public string EmpresaId { get; set; }
        public string nombre { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool BloqueoInfoCredito { get; set; }
        public Nullable<bool> FlagTodosAsesores { get; set; }
        public Nullable<bool> FlagUsuarioOficina { get; set; }
        public Nullable<bool> FlagAdministradorProductos { get; set; }
        public Nullable<bool> SesionActiva { get; set; }
        public bool FlagBodegaEspecifico { get; set; }
        public Nullable<bool> CorreoDevolucion { get; set; }
        public string Correo { get; set; }
        public Nullable<int> CorrelativoRecibos { get; set; }
        public string InicialesNombre { get; set; }
    
        public virtual Empresa Empresa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PantallasxUsuario> PantallasxUsuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuario_Rol> Usuario_Rol { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuarios_Empresas> Usuarios_Empresas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Secciones_Usuarios> Secciones_Usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Respuestas> Respuestas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LogSesion> LogSesion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuarios_Asesores> Usuarios_Asesores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MotivosDevolucion> MotivosDevolucion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MotivosDevolucionDetalle> MotivosDevolucionDetalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MotivosDevConAprobacion> MotivosDevConAprobacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MotivosDevConAprobacion> MotivosDevConAprobacion1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MotivosDevConAprobacion> MotivosDevConAprobacion2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AprobacionDevoluciones> AprobacionDevoluciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AprobacionDevoluciones> AprobacionDevoluciones1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AprobacionDevoluciones> AprobacionDevoluciones2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Devolucion> Devolucion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PromesaPago> PromesaPago { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BitacoraNoVentaEnVisitas> BitacoraNoVentaEnVisitas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsuarioLinea> UsuarioLinea { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventariosCliente> InventariosCliente { get; set; }
    }
}
