//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario_Rol
    {
        public int Id { get; set; }
        public int usuarioId { get; set; }
        public int rolId { get; set; }
        public bool status { get; set; }
        public string createdBy { get; set; }
        public System.DateTime createdDate { get; set; }
        public string editedBy { get; set; }
        public System.DateTime editedDate { get; set; }
    
        public virtual Roles Roles { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
