//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_AtributosxColeccion
    {
        public int IdColeccion { get; set; }
        public string CodigoColeccion { get; set; }
        public string Descripcion1 { get; set; }
        public string Descripcion2 { get; set; }
        public string IdLinea { get; set; }
        public string CodigoAtributo { get; set; }
    }
}
