//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ColeccionesBodegaEspecifico
    {
        public int IdColeccion { get; set; }
        public string CodigoColeccion { get; set; }
        public string Nombre { get; set; }
        public string ColeccionTipo { get; set; }
        public string EmpresaId { get; set; }
        public Nullable<System.DateTime> DisenoInicio { get; set; }
        public Nullable<System.DateTime> DisenoFinal { get; set; }
        public Nullable<System.DateTime> EntregaInicio { get; set; }
        public Nullable<System.DateTime> EntregaFinal { get; set; }
        public Nullable<int> Estatus { get; set; }
        public Nullable<System.DateTime> ProduccionInicio { get; set; }
        public Nullable<System.DateTime> ProduccionFinal { get; set; }
        public Nullable<System.DateTime> VentaInicio { get; set; }
        public Nullable<System.DateTime> VentaFinal { get; set; }
        public string FotoPortada { get; set; }
        public Nullable<System.DateTime> FechaUltSincronizacion { get; set; }
        public string Sitio { get; set; }
        public string Almacen { get; set; }
    }
}
