//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ClientesxRuta
    {
        public string CodigoCliente { get; set; }
        public string EmpresaId { get; set; }
        public string Nombre { get; set; }
        public string Zona { get; set; }
        public string ComunidadAutonoma { get; set; }
        public string GrupoPrecio { get; set; }
        public string GrupoCliente { get; set; }
        public string Descuento { get; set; }
        public string Direccion { get; set; }
        public string IdMoneda { get; set; }
        public string FacturacionEntrega { get; set; }
        public Nullable<decimal> Latitud { get; set; }
        public Nullable<decimal> Longitud { get; set; }
        public string Ruta { get; set; }
    }
}
