//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ClientesxRuta
    {
        public string CodigoCliente { get; set; }
        public string EmpresaId { get; set; }
        public string Nombre { get; set; }
        public string Zona { get; set; }
        public string ComunidadAutonoma { get; set; }
        public string GrupoPrecio { get; set; }
        public string GrupoCliente { get; set; }
        public string Descuento { get; set; }
        public string Direccion { get; set; }
        public string IdMoneda { get; set; }
        public string FacturacionEntrega { get; set; }
        public Nullable<decimal> Latitud { get; set; }
        public Nullable<decimal> Longitud { get; set; }
        public string Ruta { get; set; }
    }
}
