//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ColeccionesBodegaEspecifico
    {
        public int IdColeccion { get; set; }
        public string CodigoColeccion { get; set; }
        public string Nombre { get; set; }
        public string ColeccionTipo { get; set; }
        public string EmpresaId { get; set; }
        public Nullable<System.DateTime> DisenoInicio { get; set; }
        public Nullable<System.DateTime> DisenoFinal { get; set; }
        public Nullable<System.DateTime> EntregaInicio { get; set; }
        public Nullable<System.DateTime> EntregaFinal { get; set; }
        public Nullable<int> Estatus { get; set; }
        public Nullable<System.DateTime> ProduccionInicio { get; set; }
        public Nullable<System.DateTime> ProduccionFinal { get; set; }
        public Nullable<System.DateTime> VentaInicio { get; set; }
        public Nullable<System.DateTime> VentaFinal { get; set; }
        public string FotoPortada { get; set; }
        public Nullable<System.DateTime> FechaUltSincronizacion { get; set; }
        public string Sitio { get; set; }
        public string Almacen { get; set; }
    }
}
