//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBData.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_TallasxProducto
    {
        public int IdProducto { get; set; }
        public int IdColeccion { get; set; }
        public string CodigoProducto { get; set; }
        public string CodigoTalla { get; set; }
        public Nullable<decimal> orden { get; set; }
        public string Descripcion { get; set; }
        public string CodigoGrupoTalla { get; set; }
    }
}
