//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proxy
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class AxProduccionEntities : DbContext
    {
        public AxProduccionEntities()
            : base("name=AxProduccionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<IMEmpresasTransporte_Result> IMEmpresasTransporte(string dataareaid)
        {
            var dataareaidParameter = dataareaid != null ?
                new ObjectParameter("dataareaid", dataareaid) :
                new ObjectParameter("dataareaid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IMEmpresasTransporte_Result>("IMEmpresasTransporte", dataareaidParameter);
        }
    
        public virtual ObjectResult<IMObtenerComunidadAutonoma_Result> IMObtenerComunidadAutonoma(string pAIS)
        {
            var pAISParameter = pAIS != null ?
                new ObjectParameter("PAIS", pAIS) :
                new ObjectParameter("PAIS", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IMObtenerComunidadAutonoma_Result>("IMObtenerComunidadAutonoma", pAISParameter);
        }
    
        public virtual ObjectResult<IMObtenerPrecioCaja_Result> IMObtenerPrecioCaja(string dataareaid)
        {
            var dataareaidParameter = dataareaid != null ?
                new ObjectParameter("dataareaid", dataareaid) :
                new ObjectParameter("dataareaid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IMObtenerPrecioCaja_Result>("IMObtenerPrecioCaja", dataareaidParameter);
        }
    
        public virtual ObjectResult<IMObtenerGrupoImpuestoArticulos_Result> IMObtenerGrupoImpuestoArticulos(string pAIS)
        {
            var pAISParameter = pAIS != null ?
                new ObjectParameter("PAIS", pAIS) :
                new ObjectParameter("PAIS", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IMObtenerGrupoImpuestoArticulos_Result>("IMObtenerGrupoImpuestoArticulos", pAISParameter);
        }
    
        public virtual ObjectResult<IMObtenerGrupoImpuestoClientes_Result> IMObtenerGrupoImpuestoClientes(string pais)
        {
            var paisParameter = pais != null ?
                new ObjectParameter("Pais", pais) :
                new ObjectParameter("Pais", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IMObtenerGrupoImpuestoClientes_Result>("IMObtenerGrupoImpuestoClientes", paisParameter);
        }
    
        public virtual ObjectResult<IM_ObtenerEmpresas_Result> IM_ObtenerEmpresas()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IM_ObtenerEmpresas_Result>("IM_ObtenerEmpresas");
        }
    }
}
